// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: yzpm.proto

package com.msg;

/**
 * <pre>
 *分配客单 给指定老师
 * </pre>
 *
 * Protobuf type {@code C_AssignOrderToTeacher_3010}
 */
public  final class C_AssignOrderToTeacher_3010 extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:C_AssignOrderToTeacher_3010)
    C_AssignOrderToTeacher_3010OrBuilder {
private static final long serialVersionUID = 0L;
  // Use C_AssignOrderToTeacher_3010.newBuilder() to construct.
  private C_AssignOrderToTeacher_3010(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private C_AssignOrderToTeacher_3010() {
    orderId_ = emptyLongList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new C_AssignOrderToTeacher_3010();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private C_AssignOrderToTeacher_3010(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 9: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              orderId_ = newLongList();
              mutable_bitField0_ |= 0x00000001;
            }
            orderId_.addLong(input.readFixed64());
            break;
          }
          case 10: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
              orderId_ = newLongList();
              mutable_bitField0_ |= 0x00000001;
            }
            while (input.getBytesUntilLimit() > 0) {
              orderId_.addLong(input.readFixed64());
            }
            input.popLimit(limit);
            break;
          }
          case 17: {

            toTeacherId_ = input.readFixed64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        orderId_.makeImmutable(); // C
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.msg.YZPM.internal_static_C_AssignOrderToTeacher_3010_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.msg.YZPM.internal_static_C_AssignOrderToTeacher_3010_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.msg.C_AssignOrderToTeacher_3010.class, com.msg.C_AssignOrderToTeacher_3010.Builder.class);
  }

  public static final int ORDERID_FIELD_NUMBER = 1;
  private com.google.protobuf.Internal.LongList orderId_;
  /**
   * <pre>
   *客单唯一id
   * </pre>
   *
   * <code>repeated fixed64 orderId = 1;</code>
   * @return A list containing the orderId.
   */
  public java.util.List<java.lang.Long>
      getOrderIdList() {
    return orderId_;
  }
  /**
   * <pre>
   *客单唯一id
   * </pre>
   *
   * <code>repeated fixed64 orderId = 1;</code>
   * @return The count of orderId.
   */
  public int getOrderIdCount() {
    return orderId_.size();
  }
  /**
   * <pre>
   *客单唯一id
   * </pre>
   *
   * <code>repeated fixed64 orderId = 1;</code>
   * @param index The index of the element to return.
   * @return The orderId at the given index.
   */
  public long getOrderId(int index) {
    return orderId_.getLong(index);
  }
  private int orderIdMemoizedSerializedSize = -1;

  public static final int TOTEACHERID_FIELD_NUMBER = 2;
  private long toTeacherId_;
  /**
   * <pre>
   *分配给老师id
   * </pre>
   *
   * <code>fixed64 toTeacherId = 2;</code>
   * @return The toTeacherId.
   */
  public long getToTeacherId() {
    return toTeacherId_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (getOrderIdList().size() > 0) {
      output.writeUInt32NoTag(10);
      output.writeUInt32NoTag(orderIdMemoizedSerializedSize);
    }
    for (int i = 0; i < orderId_.size(); i++) {
      output.writeFixed64NoTag(orderId_.getLong(i));
    }
    if (toTeacherId_ != 0L) {
      output.writeFixed64(2, toTeacherId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      dataSize = 8 * getOrderIdList().size();
      size += dataSize;
      if (!getOrderIdList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      orderIdMemoizedSerializedSize = dataSize;
    }
    if (toTeacherId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeFixed64Size(2, toTeacherId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.msg.C_AssignOrderToTeacher_3010)) {
      return super.equals(obj);
    }
    com.msg.C_AssignOrderToTeacher_3010 other = (com.msg.C_AssignOrderToTeacher_3010) obj;

    if (!getOrderIdList()
        .equals(other.getOrderIdList())) return false;
    if (getToTeacherId()
        != other.getToTeacherId()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getOrderIdCount() > 0) {
      hash = (37 * hash) + ORDERID_FIELD_NUMBER;
      hash = (53 * hash) + getOrderIdList().hashCode();
    }
    hash = (37 * hash) + TOTEACHERID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getToTeacherId());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.msg.C_AssignOrderToTeacher_3010 parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.msg.C_AssignOrderToTeacher_3010 parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.msg.C_AssignOrderToTeacher_3010 parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.msg.C_AssignOrderToTeacher_3010 parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.msg.C_AssignOrderToTeacher_3010 parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.msg.C_AssignOrderToTeacher_3010 parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.msg.C_AssignOrderToTeacher_3010 parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.msg.C_AssignOrderToTeacher_3010 parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.msg.C_AssignOrderToTeacher_3010 parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.msg.C_AssignOrderToTeacher_3010 parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.msg.C_AssignOrderToTeacher_3010 parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.msg.C_AssignOrderToTeacher_3010 parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.msg.C_AssignOrderToTeacher_3010 prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *分配客单 给指定老师
   * </pre>
   *
   * Protobuf type {@code C_AssignOrderToTeacher_3010}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:C_AssignOrderToTeacher_3010)
      com.msg.C_AssignOrderToTeacher_3010OrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.msg.YZPM.internal_static_C_AssignOrderToTeacher_3010_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.msg.YZPM.internal_static_C_AssignOrderToTeacher_3010_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.msg.C_AssignOrderToTeacher_3010.class, com.msg.C_AssignOrderToTeacher_3010.Builder.class);
    }

    // Construct using com.msg.C_AssignOrderToTeacher_3010.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      orderId_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000001);
      toTeacherId_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.msg.YZPM.internal_static_C_AssignOrderToTeacher_3010_descriptor;
    }

    @java.lang.Override
    public com.msg.C_AssignOrderToTeacher_3010 getDefaultInstanceForType() {
      return com.msg.C_AssignOrderToTeacher_3010.getDefaultInstance();
    }

    @java.lang.Override
    public com.msg.C_AssignOrderToTeacher_3010 build() {
      com.msg.C_AssignOrderToTeacher_3010 result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.msg.C_AssignOrderToTeacher_3010 buildPartial() {
      com.msg.C_AssignOrderToTeacher_3010 result = new com.msg.C_AssignOrderToTeacher_3010(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) != 0)) {
        orderId_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.orderId_ = orderId_;
      result.toTeacherId_ = toTeacherId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.msg.C_AssignOrderToTeacher_3010) {
        return mergeFrom((com.msg.C_AssignOrderToTeacher_3010)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.msg.C_AssignOrderToTeacher_3010 other) {
      if (other == com.msg.C_AssignOrderToTeacher_3010.getDefaultInstance()) return this;
      if (!other.orderId_.isEmpty()) {
        if (orderId_.isEmpty()) {
          orderId_ = other.orderId_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureOrderIdIsMutable();
          orderId_.addAll(other.orderId_);
        }
        onChanged();
      }
      if (other.getToTeacherId() != 0L) {
        setToTeacherId(other.getToTeacherId());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.msg.C_AssignOrderToTeacher_3010 parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.msg.C_AssignOrderToTeacher_3010) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.Internal.LongList orderId_ = emptyLongList();
    private void ensureOrderIdIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        orderId_ = mutableCopy(orderId_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <pre>
     *客单唯一id
     * </pre>
     *
     * <code>repeated fixed64 orderId = 1;</code>
     * @return A list containing the orderId.
     */
    public java.util.List<java.lang.Long>
        getOrderIdList() {
      return ((bitField0_ & 0x00000001) != 0) ?
               java.util.Collections.unmodifiableList(orderId_) : orderId_;
    }
    /**
     * <pre>
     *客单唯一id
     * </pre>
     *
     * <code>repeated fixed64 orderId = 1;</code>
     * @return The count of orderId.
     */
    public int getOrderIdCount() {
      return orderId_.size();
    }
    /**
     * <pre>
     *客单唯一id
     * </pre>
     *
     * <code>repeated fixed64 orderId = 1;</code>
     * @param index The index of the element to return.
     * @return The orderId at the given index.
     */
    public long getOrderId(int index) {
      return orderId_.getLong(index);
    }
    /**
     * <pre>
     *客单唯一id
     * </pre>
     *
     * <code>repeated fixed64 orderId = 1;</code>
     * @param index The index to set the value at.
     * @param value The orderId to set.
     * @return This builder for chaining.
     */
    public Builder setOrderId(
        int index, long value) {
      ensureOrderIdIsMutable();
      orderId_.setLong(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *客单唯一id
     * </pre>
     *
     * <code>repeated fixed64 orderId = 1;</code>
     * @param value The orderId to add.
     * @return This builder for chaining.
     */
    public Builder addOrderId(long value) {
      ensureOrderIdIsMutable();
      orderId_.addLong(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *客单唯一id
     * </pre>
     *
     * <code>repeated fixed64 orderId = 1;</code>
     * @param values The orderId to add.
     * @return This builder for chaining.
     */
    public Builder addAllOrderId(
        java.lang.Iterable<? extends java.lang.Long> values) {
      ensureOrderIdIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, orderId_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *客单唯一id
     * </pre>
     *
     * <code>repeated fixed64 orderId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearOrderId() {
      orderId_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }

    private long toTeacherId_ ;
    /**
     * <pre>
     *分配给老师id
     * </pre>
     *
     * <code>fixed64 toTeacherId = 2;</code>
     * @return The toTeacherId.
     */
    public long getToTeacherId() {
      return toTeacherId_;
    }
    /**
     * <pre>
     *分配给老师id
     * </pre>
     *
     * <code>fixed64 toTeacherId = 2;</code>
     * @param value The toTeacherId to set.
     * @return This builder for chaining.
     */
    public Builder setToTeacherId(long value) {
      
      toTeacherId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *分配给老师id
     * </pre>
     *
     * <code>fixed64 toTeacherId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearToTeacherId() {
      
      toTeacherId_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:C_AssignOrderToTeacher_3010)
  }

  // @@protoc_insertion_point(class_scope:C_AssignOrderToTeacher_3010)
  private static final com.msg.C_AssignOrderToTeacher_3010 DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.msg.C_AssignOrderToTeacher_3010();
  }

  public static com.msg.C_AssignOrderToTeacher_3010 getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<C_AssignOrderToTeacher_3010>
      PARSER = new com.google.protobuf.AbstractParser<C_AssignOrderToTeacher_3010>() {
    @java.lang.Override
    public C_AssignOrderToTeacher_3010 parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new C_AssignOrderToTeacher_3010(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<C_AssignOrderToTeacher_3010> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<C_AssignOrderToTeacher_3010> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.msg.C_AssignOrderToTeacher_3010 getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

