// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: yzpm.proto

package com.msg;

public interface C_CreateFormInfo_5002OrBuilder extends
    // @@protoc_insertion_point(interface_extends:C_CreateFormInfo_5002)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *当前登录老师的 UsersRes.id  // OrderInfo orderInfo = 1;    //
   * </pre>
   *
   * <code>int64 teacherId = 1;</code>
   * @return The teacherId.
   */
  long getTeacherId();

  /**
   * <pre>
   *通过客单信息 查询志愿信息
   * </pre>
   *
   * <code>fixed64 orderId = 2;</code>
   * @return The orderId.
   */
  long getOrderId();

  /**
   * <pre>
   * 表单名  //FormInfo formInfo = 3;      //服务 添加信息时候， 需要把MajorId转成MajorHistDB——id
   * </pre>
   *
   * <code>string formName = 3;</code>
   * @return The formName.
   */
  java.lang.String getFormName();
  /**
   * <pre>
   * 表单名  //FormInfo formInfo = 3;      //服务 添加信息时候， 需要把MajorId转成MajorHistDB——id
   * </pre>
   *
   * <code>string formName = 3;</code>
   * @return The bytes for formName.
   */
  com.google.protobuf.ByteString
      getFormNameBytes();

  /**
   * <pre>
   * 专业组信息
   * </pre>
   *
   * <code>.FormDetailInfo detail = 4;</code>
   * @return Whether the detail field is set.
   */
  boolean hasDetail();
  /**
   * <pre>
   * 专业组信息
   * </pre>
   *
   * <code>.FormDetailInfo detail = 4;</code>
   * @return The detail.
   */
  com.msg.FormDetailInfo getDetail();
  /**
   * <pre>
   * 专业组信息
   * </pre>
   *
   * <code>.FormDetailInfo detail = 4;</code>
   */
  com.msg.FormDetailInfoOrBuilder getDetailOrBuilder();

  /**
   * <pre>
   *批次: 1: 本科A,2:本科B, 3: 提前批本A, 4:提前批本B
   * </pre>
   *
   * <code>int32 pici = 5;</code>
   * @return The pici.
   */
  int getPici();

  /**
   * <pre>
   *志愿表唯一id, 如果是因为志愿表锁定, 重新生成志愿, 需要输入当前被锁定志愿的formId
   * </pre>
   *
   * <code>fixed64 lockedFormId = 6;</code>
   * @return The lockedFormId.
   */
  long getLockedFormId();

  /**
   * <pre>
   *志愿年份
   * </pre>
   *
   * <code>string examYear = 7;</code>
   * @return The examYear.
   */
  java.lang.String getExamYear();
  /**
   * <pre>
   *志愿年份
   * </pre>
   *
   * <code>string examYear = 7;</code>
   * @return The bytes for examYear.
   */
  com.google.protobuf.ByteString
      getExamYearBytes();
}
