// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: yzpm.proto

package com.msg;

/**
 * <pre>
 *创建客单信息
 * </pre>
 *
 * Protobuf type {@code C_CreateOrderInfo_3002}
 */
public  final class C_CreateOrderInfo_3002 extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:C_CreateOrderInfo_3002)
    C_CreateOrderInfo_3002OrBuilder {
private static final long serialVersionUID = 0L;
  // Use C_CreateOrderInfo_3002.newBuilder() to construct.
  private C_CreateOrderInfo_3002(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private C_CreateOrderInfo_3002() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new C_CreateOrderInfo_3002();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private C_CreateOrderInfo_3002(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            teacherId_ = input.readInt64();
            break;
          }
          case 18: {
            com.msg.ClientInfo.Builder subBuilder = null;
            if (clientInfo_ != null) {
              subBuilder = clientInfo_.toBuilder();
            }
            clientInfo_ = input.readMessage(com.msg.ClientInfo.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(clientInfo_);
              clientInfo_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.msg.YZPM.internal_static_C_CreateOrderInfo_3002_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.msg.YZPM.internal_static_C_CreateOrderInfo_3002_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.msg.C_CreateOrderInfo_3002.class, com.msg.C_CreateOrderInfo_3002.Builder.class);
  }

  public static final int TEACHERID_FIELD_NUMBER = 1;
  private long teacherId_;
  /**
   * <pre>
   *当前登录老师的 UsersRes.id  // OrderInfo orderInfo = 1;    //
   * </pre>
   *
   * <code>int64 teacherId = 1;</code>
   * @return The teacherId.
   */
  public long getTeacherId() {
    return teacherId_;
  }

  public static final int CLIENTINFO_FIELD_NUMBER = 2;
  private com.msg.ClientInfo clientInfo_;
  /**
   * <pre>
   *客单对应用户信息
   * </pre>
   *
   * <code>.ClientInfo clientInfo = 2;</code>
   * @return Whether the clientInfo field is set.
   */
  public boolean hasClientInfo() {
    return clientInfo_ != null;
  }
  /**
   * <pre>
   *客单对应用户信息
   * </pre>
   *
   * <code>.ClientInfo clientInfo = 2;</code>
   * @return The clientInfo.
   */
  public com.msg.ClientInfo getClientInfo() {
    return clientInfo_ == null ? com.msg.ClientInfo.getDefaultInstance() : clientInfo_;
  }
  /**
   * <pre>
   *客单对应用户信息
   * </pre>
   *
   * <code>.ClientInfo clientInfo = 2;</code>
   */
  public com.msg.ClientInfoOrBuilder getClientInfoOrBuilder() {
    return getClientInfo();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (teacherId_ != 0L) {
      output.writeInt64(1, teacherId_);
    }
    if (clientInfo_ != null) {
      output.writeMessage(2, getClientInfo());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (teacherId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, teacherId_);
    }
    if (clientInfo_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getClientInfo());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.msg.C_CreateOrderInfo_3002)) {
      return super.equals(obj);
    }
    com.msg.C_CreateOrderInfo_3002 other = (com.msg.C_CreateOrderInfo_3002) obj;

    if (getTeacherId()
        != other.getTeacherId()) return false;
    if (hasClientInfo() != other.hasClientInfo()) return false;
    if (hasClientInfo()) {
      if (!getClientInfo()
          .equals(other.getClientInfo())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TEACHERID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTeacherId());
    if (hasClientInfo()) {
      hash = (37 * hash) + CLIENTINFO_FIELD_NUMBER;
      hash = (53 * hash) + getClientInfo().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.msg.C_CreateOrderInfo_3002 parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.msg.C_CreateOrderInfo_3002 parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.msg.C_CreateOrderInfo_3002 parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.msg.C_CreateOrderInfo_3002 parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.msg.C_CreateOrderInfo_3002 parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.msg.C_CreateOrderInfo_3002 parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.msg.C_CreateOrderInfo_3002 parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.msg.C_CreateOrderInfo_3002 parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.msg.C_CreateOrderInfo_3002 parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.msg.C_CreateOrderInfo_3002 parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.msg.C_CreateOrderInfo_3002 parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.msg.C_CreateOrderInfo_3002 parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.msg.C_CreateOrderInfo_3002 prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *创建客单信息
   * </pre>
   *
   * Protobuf type {@code C_CreateOrderInfo_3002}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:C_CreateOrderInfo_3002)
      com.msg.C_CreateOrderInfo_3002OrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.msg.YZPM.internal_static_C_CreateOrderInfo_3002_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.msg.YZPM.internal_static_C_CreateOrderInfo_3002_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.msg.C_CreateOrderInfo_3002.class, com.msg.C_CreateOrderInfo_3002.Builder.class);
    }

    // Construct using com.msg.C_CreateOrderInfo_3002.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      teacherId_ = 0L;

      if (clientInfoBuilder_ == null) {
        clientInfo_ = null;
      } else {
        clientInfo_ = null;
        clientInfoBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.msg.YZPM.internal_static_C_CreateOrderInfo_3002_descriptor;
    }

    @java.lang.Override
    public com.msg.C_CreateOrderInfo_3002 getDefaultInstanceForType() {
      return com.msg.C_CreateOrderInfo_3002.getDefaultInstance();
    }

    @java.lang.Override
    public com.msg.C_CreateOrderInfo_3002 build() {
      com.msg.C_CreateOrderInfo_3002 result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.msg.C_CreateOrderInfo_3002 buildPartial() {
      com.msg.C_CreateOrderInfo_3002 result = new com.msg.C_CreateOrderInfo_3002(this);
      result.teacherId_ = teacherId_;
      if (clientInfoBuilder_ == null) {
        result.clientInfo_ = clientInfo_;
      } else {
        result.clientInfo_ = clientInfoBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.msg.C_CreateOrderInfo_3002) {
        return mergeFrom((com.msg.C_CreateOrderInfo_3002)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.msg.C_CreateOrderInfo_3002 other) {
      if (other == com.msg.C_CreateOrderInfo_3002.getDefaultInstance()) return this;
      if (other.getTeacherId() != 0L) {
        setTeacherId(other.getTeacherId());
      }
      if (other.hasClientInfo()) {
        mergeClientInfo(other.getClientInfo());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.msg.C_CreateOrderInfo_3002 parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.msg.C_CreateOrderInfo_3002) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long teacherId_ ;
    /**
     * <pre>
     *当前登录老师的 UsersRes.id  // OrderInfo orderInfo = 1;    //
     * </pre>
     *
     * <code>int64 teacherId = 1;</code>
     * @return The teacherId.
     */
    public long getTeacherId() {
      return teacherId_;
    }
    /**
     * <pre>
     *当前登录老师的 UsersRes.id  // OrderInfo orderInfo = 1;    //
     * </pre>
     *
     * <code>int64 teacherId = 1;</code>
     * @param value The teacherId to set.
     * @return This builder for chaining.
     */
    public Builder setTeacherId(long value) {
      
      teacherId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *当前登录老师的 UsersRes.id  // OrderInfo orderInfo = 1;    //
     * </pre>
     *
     * <code>int64 teacherId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTeacherId() {
      
      teacherId_ = 0L;
      onChanged();
      return this;
    }

    private com.msg.ClientInfo clientInfo_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.msg.ClientInfo, com.msg.ClientInfo.Builder, com.msg.ClientInfoOrBuilder> clientInfoBuilder_;
    /**
     * <pre>
     *客单对应用户信息
     * </pre>
     *
     * <code>.ClientInfo clientInfo = 2;</code>
     * @return Whether the clientInfo field is set.
     */
    public boolean hasClientInfo() {
      return clientInfoBuilder_ != null || clientInfo_ != null;
    }
    /**
     * <pre>
     *客单对应用户信息
     * </pre>
     *
     * <code>.ClientInfo clientInfo = 2;</code>
     * @return The clientInfo.
     */
    public com.msg.ClientInfo getClientInfo() {
      if (clientInfoBuilder_ == null) {
        return clientInfo_ == null ? com.msg.ClientInfo.getDefaultInstance() : clientInfo_;
      } else {
        return clientInfoBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *客单对应用户信息
     * </pre>
     *
     * <code>.ClientInfo clientInfo = 2;</code>
     */
    public Builder setClientInfo(com.msg.ClientInfo value) {
      if (clientInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        clientInfo_ = value;
        onChanged();
      } else {
        clientInfoBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     *客单对应用户信息
     * </pre>
     *
     * <code>.ClientInfo clientInfo = 2;</code>
     */
    public Builder setClientInfo(
        com.msg.ClientInfo.Builder builderForValue) {
      if (clientInfoBuilder_ == null) {
        clientInfo_ = builderForValue.build();
        onChanged();
      } else {
        clientInfoBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     *客单对应用户信息
     * </pre>
     *
     * <code>.ClientInfo clientInfo = 2;</code>
     */
    public Builder mergeClientInfo(com.msg.ClientInfo value) {
      if (clientInfoBuilder_ == null) {
        if (clientInfo_ != null) {
          clientInfo_ =
            com.msg.ClientInfo.newBuilder(clientInfo_).mergeFrom(value).buildPartial();
        } else {
          clientInfo_ = value;
        }
        onChanged();
      } else {
        clientInfoBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     *客单对应用户信息
     * </pre>
     *
     * <code>.ClientInfo clientInfo = 2;</code>
     */
    public Builder clearClientInfo() {
      if (clientInfoBuilder_ == null) {
        clientInfo_ = null;
        onChanged();
      } else {
        clientInfo_ = null;
        clientInfoBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     *客单对应用户信息
     * </pre>
     *
     * <code>.ClientInfo clientInfo = 2;</code>
     */
    public com.msg.ClientInfo.Builder getClientInfoBuilder() {
      
      onChanged();
      return getClientInfoFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *客单对应用户信息
     * </pre>
     *
     * <code>.ClientInfo clientInfo = 2;</code>
     */
    public com.msg.ClientInfoOrBuilder getClientInfoOrBuilder() {
      if (clientInfoBuilder_ != null) {
        return clientInfoBuilder_.getMessageOrBuilder();
      } else {
        return clientInfo_ == null ?
            com.msg.ClientInfo.getDefaultInstance() : clientInfo_;
      }
    }
    /**
     * <pre>
     *客单对应用户信息
     * </pre>
     *
     * <code>.ClientInfo clientInfo = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.msg.ClientInfo, com.msg.ClientInfo.Builder, com.msg.ClientInfoOrBuilder> 
        getClientInfoFieldBuilder() {
      if (clientInfoBuilder_ == null) {
        clientInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.msg.ClientInfo, com.msg.ClientInfo.Builder, com.msg.ClientInfoOrBuilder>(
                getClientInfo(),
                getParentForChildren(),
                isClean());
        clientInfo_ = null;
      }
      return clientInfoBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:C_CreateOrderInfo_3002)
  }

  // @@protoc_insertion_point(class_scope:C_CreateOrderInfo_3002)
  private static final com.msg.C_CreateOrderInfo_3002 DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.msg.C_CreateOrderInfo_3002();
  }

  public static com.msg.C_CreateOrderInfo_3002 getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<C_CreateOrderInfo_3002>
      PARSER = new com.google.protobuf.AbstractParser<C_CreateOrderInfo_3002>() {
    @java.lang.Override
    public C_CreateOrderInfo_3002 parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new C_CreateOrderInfo_3002(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<C_CreateOrderInfo_3002> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<C_CreateOrderInfo_3002> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.msg.C_CreateOrderInfo_3002 getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

