// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: yzpm.proto

package com.msg;

public interface C_GetOrderInfoByPage_3000OrBuilder extends
    // @@protoc_insertion_point(interface_extends:C_GetOrderInfoByPage_3000)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *客户手机号  &amp;&amp;//授权可查看的教师名; 服务器按教师名查询，需要先找对应教师的id，再查OderInfo表
   * </pre>
   *
   * <code>string tel = 1;</code>
   * @return The tel.
   */
  java.lang.String getTel();
  /**
   * <pre>
   *客户手机号  &amp;&amp;//授权可查看的教师名; 服务器按教师名查询，需要先找对应教师的id，再查OderInfo表
   * </pre>
   *
   * <code>string tel = 1;</code>
   * @return The bytes for tel.
   */
  com.google.protobuf.ByteString
      getTelBytes();

  /**
   * <pre>
   *省份
   * </pre>
   *
   * <code>string province = 3;</code>
   * @return The province.
   */
  java.lang.String getProvince();
  /**
   * <pre>
   *省份
   * </pre>
   *
   * <code>string province = 3;</code>
   * @return The bytes for province.
   */
  com.google.protobuf.ByteString
      getProvinceBytes();

  /**
   * <pre>
   *状态   0:待处理（等待创建方案）1:已处理（等待审核方案）2:已审核（等待用户确认）3:已完成（用户已确认   -1:无状态
   * </pre>
   *
   * <code>int32 status = 4;</code>
   * @return The status.
   */
  int getStatus();

  /**
   * <pre>
   *高考年份
   * </pre>
   *
   * <code>string year = 5;</code>
   * @return The year.
   */
  java.lang.String getYear();
  /**
   * <pre>
   *高考年份
   * </pre>
   *
   * <code>string year = 5;</code>
   * @return The bytes for year.
   */
  com.google.protobuf.ByteString
      getYearBytes();

  /**
   * <pre>
   *客户名
   * </pre>
   *
   * <code>string clientName = 6;</code>
   * @return The clientName.
   */
  java.lang.String getClientName();
  /**
   * <pre>
   *客户名
   * </pre>
   *
   * <code>string clientName = 6;</code>
   * @return The bytes for clientName.
   */
  com.google.protobuf.ByteString
      getClientNameBytes();

  /**
   * <pre>
   *查询页码
   * </pre>
   *
   * <code>int32 page = 7;</code>
   * @return The page.
   */
  int getPage();

  /**
   * <pre>
   *每页显示条数
   * </pre>
   *
   * <code>int32 limit = 8;</code>
   * @return The limit.
   */
  int getLimit();

  /**
   * <pre>
   *志愿填报界面，需要用这个UsersRes.id查询当前用户【老师】被授权查看的客单 ; 默认-1;
   * </pre>
   *
   * <code>int64 teacherId = 9;</code>
   * @return The teacherId.
   */
  long getTeacherId();

  /**
   * <pre>
   *体检限报选项,  0: 所有   1: 正常  2: 存在限报 ;
   * </pre>
   *
   * <code>int32 physicLimitation = 10;</code>
   * @return The physicLimitation.
   */
  int getPhysicLimitation();

  /**
   * <pre>
   *是否包含 删除的数据  1:包含删除的, 0:不包含删除的
   * </pre>
   *
   * <code>int32 incluDeleted = 11;</code>
   * @return The incluDeleted.
   */
  int getIncluDeleted();
}
