// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: yzpm.proto

package com.msg;

public interface C_GetFormInfoDetail_5006OrBuilder extends
    // @@protoc_insertion_point(interface_extends:C_GetFormInfoDetail_5006)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * </pre>
   *
   * <code>fixed64 formId = 1;</code>
   * @return The formId.
   */
  long getFormId();

  /**
   * <pre>
   * </pre>
   *
   * <code>int64 teacherId = 4;</code>
   * @return The teacherId.
   */
  long getTeacherId();
}
