// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: yzpm.proto

package com.msg;

public interface C_GetMajorsOfUniByIcon_4006OrBuilder extends
    // @@protoc_insertion_point(interface_extends:C_GetMajorsOfUniByIcon_4006)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *学校名字
   * </pre>
   *
   * <code>string schoolName = 1;</code>
   * @return The schoolName.
   */
  java.lang.String getSchoolName();
  /**
   * <pre>
   *学校名字
   * </pre>
   *
   * <code>string schoolName = 1;</code>
   * @return The bytes for schoolName.
   */
  com.google.protobuf.ByteString
      getSchoolNameBytes();

  /**
   * <pre>
   *点击的图标的icon id
   * </pre>
   *
   * <code>string majorIconId = 2;</code>
   * @return The majorIconId.
   */
  java.lang.String getMajorIconId();
  /**
   * <pre>
   *点击的图标的icon id
   * </pre>
   *
   * <code>string majorIconId = 2;</code>
   * @return The bytes for majorIconId.
   */
  com.google.protobuf.ByteString
      getMajorIconIdBytes();
}
