// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: yzpm.proto

package com.msg;

public interface C_GetTeacherInfoByPage_2000OrBuilder extends
    // @@protoc_insertion_point(interface_extends:C_GetTeacherInfoByPage_2000)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *手机号
   * </pre>
   *
   * <code>string tel = 1;</code>
   * @return The tel.
   */
  java.lang.String getTel();
  /**
   * <pre>
   *手机号
   * </pre>
   *
   * <code>string tel = 1;</code>
   * @return The bytes for tel.
   */
  com.google.protobuf.ByteString
      getTelBytes();

  /**
   * <pre>
   *教师名
   * </pre>
   *
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   *教师名
   * </pre>
   *
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   *教师类型
   * </pre>
   *
   * <code>int32 type = 3;</code>
   * @return The type.
   */
  int getType();

  /**
   * <pre>
   *查询页码
   * </pre>
   *
   * <code>int32 page = 4;</code>
   * @return The page.
   */
  int getPage();

  /**
   * <pre>
   *每页显示条数
   * </pre>
   *
   * <code>int32 limit = 5;</code>
   * @return The limit.
   */
  int getLimit();

  /**
   * <pre>
   *需要用这个UsersRes.id查询当前用户【老师】被授权查看的客单 ; 默认-1;
   * </pre>
   *
   * <code>int64 teacherId = 6;</code>
   * @return The teacherId.
   */
  long getTeacherId();
}
