// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: yzpm.proto

package com.msg;

/**
 * <pre>
 *获取志愿详情
 * </pre>
 *
 * Protobuf type {@code C_GetFormInfoDetail_5006}
 */
public  final class C_GetFormInfoDetail_5006 extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:C_GetFormInfoDetail_5006)
    C_GetFormInfoDetail_5006OrBuilder {
private static final long serialVersionUID = 0L;
  // Use C_GetFormInfoDetail_5006.newBuilder() to construct.
  private C_GetFormInfoDetail_5006(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private C_GetFormInfoDetail_5006() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new C_GetFormInfoDetail_5006();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private C_GetFormInfoDetail_5006(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 9: {

            formId_ = input.readFixed64();
            break;
          }
          case 32: {

            teacherId_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.msg.YZPM.internal_static_C_GetFormInfoDetail_5006_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.msg.YZPM.internal_static_C_GetFormInfoDetail_5006_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.msg.C_GetFormInfoDetail_5006.class, com.msg.C_GetFormInfoDetail_5006.Builder.class);
  }

  public static final int FORMID_FIELD_NUMBER = 1;
  private long formId_;
  /**
   * <pre>
   * </pre>
   *
   * <code>fixed64 formId = 1;</code>
   * @return The formId.
   */
  public long getFormId() {
    return formId_;
  }

  public static final int TEACHERID_FIELD_NUMBER = 4;
  private long teacherId_;
  /**
   * <pre>
   * </pre>
   *
   * <code>int64 teacherId = 4;</code>
   * @return The teacherId.
   */
  public long getTeacherId() {
    return teacherId_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (formId_ != 0L) {
      output.writeFixed64(1, formId_);
    }
    if (teacherId_ != 0L) {
      output.writeInt64(4, teacherId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (formId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeFixed64Size(1, formId_);
    }
    if (teacherId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, teacherId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.msg.C_GetFormInfoDetail_5006)) {
      return super.equals(obj);
    }
    com.msg.C_GetFormInfoDetail_5006 other = (com.msg.C_GetFormInfoDetail_5006) obj;

    if (getFormId()
        != other.getFormId()) return false;
    if (getTeacherId()
        != other.getTeacherId()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FORMID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getFormId());
    hash = (37 * hash) + TEACHERID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTeacherId());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.msg.C_GetFormInfoDetail_5006 parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.msg.C_GetFormInfoDetail_5006 parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.msg.C_GetFormInfoDetail_5006 parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.msg.C_GetFormInfoDetail_5006 parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.msg.C_GetFormInfoDetail_5006 parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.msg.C_GetFormInfoDetail_5006 parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.msg.C_GetFormInfoDetail_5006 parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.msg.C_GetFormInfoDetail_5006 parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.msg.C_GetFormInfoDetail_5006 parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.msg.C_GetFormInfoDetail_5006 parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.msg.C_GetFormInfoDetail_5006 parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.msg.C_GetFormInfoDetail_5006 parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.msg.C_GetFormInfoDetail_5006 prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *获取志愿详情
   * </pre>
   *
   * Protobuf type {@code C_GetFormInfoDetail_5006}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:C_GetFormInfoDetail_5006)
      com.msg.C_GetFormInfoDetail_5006OrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.msg.YZPM.internal_static_C_GetFormInfoDetail_5006_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.msg.YZPM.internal_static_C_GetFormInfoDetail_5006_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.msg.C_GetFormInfoDetail_5006.class, com.msg.C_GetFormInfoDetail_5006.Builder.class);
    }

    // Construct using com.msg.C_GetFormInfoDetail_5006.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      formId_ = 0L;

      teacherId_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.msg.YZPM.internal_static_C_GetFormInfoDetail_5006_descriptor;
    }

    @java.lang.Override
    public com.msg.C_GetFormInfoDetail_5006 getDefaultInstanceForType() {
      return com.msg.C_GetFormInfoDetail_5006.getDefaultInstance();
    }

    @java.lang.Override
    public com.msg.C_GetFormInfoDetail_5006 build() {
      com.msg.C_GetFormInfoDetail_5006 result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.msg.C_GetFormInfoDetail_5006 buildPartial() {
      com.msg.C_GetFormInfoDetail_5006 result = new com.msg.C_GetFormInfoDetail_5006(this);
      result.formId_ = formId_;
      result.teacherId_ = teacherId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.msg.C_GetFormInfoDetail_5006) {
        return mergeFrom((com.msg.C_GetFormInfoDetail_5006)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.msg.C_GetFormInfoDetail_5006 other) {
      if (other == com.msg.C_GetFormInfoDetail_5006.getDefaultInstance()) return this;
      if (other.getFormId() != 0L) {
        setFormId(other.getFormId());
      }
      if (other.getTeacherId() != 0L) {
        setTeacherId(other.getTeacherId());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.msg.C_GetFormInfoDetail_5006 parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.msg.C_GetFormInfoDetail_5006) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long formId_ ;
    /**
     * <pre>
     * </pre>
     *
     * <code>fixed64 formId = 1;</code>
     * @return The formId.
     */
    public long getFormId() {
      return formId_;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>fixed64 formId = 1;</code>
     * @param value The formId to set.
     * @return This builder for chaining.
     */
    public Builder setFormId(long value) {
      
      formId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>fixed64 formId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearFormId() {
      
      formId_ = 0L;
      onChanged();
      return this;
    }

    private long teacherId_ ;
    /**
     * <pre>
     * </pre>
     *
     * <code>int64 teacherId = 4;</code>
     * @return The teacherId.
     */
    public long getTeacherId() {
      return teacherId_;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>int64 teacherId = 4;</code>
     * @param value The teacherId to set.
     * @return This builder for chaining.
     */
    public Builder setTeacherId(long value) {
      
      teacherId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>int64 teacherId = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTeacherId() {
      
      teacherId_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:C_GetFormInfoDetail_5006)
  }

  // @@protoc_insertion_point(class_scope:C_GetFormInfoDetail_5006)
  private static final com.msg.C_GetFormInfoDetail_5006 DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.msg.C_GetFormInfoDetail_5006();
  }

  public static com.msg.C_GetFormInfoDetail_5006 getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<C_GetFormInfoDetail_5006>
      PARSER = new com.google.protobuf.AbstractParser<C_GetFormInfoDetail_5006>() {
    @java.lang.Override
    public C_GetFormInfoDetail_5006 parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new C_GetFormInfoDetail_5006(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<C_GetFormInfoDetail_5006> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<C_GetFormInfoDetail_5006> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.msg.C_GetFormInfoDetail_5006 getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

