// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: yzpm.proto

package com.msg;

public interface C_getMailVerifyCode_1008OrBuilder extends
    // @@protoc_insertion_point(interface_extends:C_getMailVerifyCode_1008)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *邮箱地址
   * </pre>
   *
   * <code>string emailAddress = 1;</code>
   * @return The emailAddress.
   */
  java.lang.String getEmailAddress();
  /**
   * <pre>
   *邮箱地址
   * </pre>
   *
   * <code>string emailAddress = 1;</code>
   * @return The bytes for emailAddress.
   */
  com.google.protobuf.ByteString
      getEmailAddressBytes();
}
