// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: yzpm.proto

package com.msg;

public interface C_UpdateFormInfo_5004OrBuilder extends
    // @@protoc_insertion_point(interface_extends:C_UpdateFormInfo_5004)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * </pre>
   *
   * <code>fixed64 formId = 1;</code>
   * @return The formId.
   */
  long getFormId();

  /**
   * <pre>
   * 表单名
   * </pre>
   *
   * <code>string formName = 2;</code>
   * @return The formName.
   */
  java.lang.String getFormName();
  /**
   * <pre>
   * 表单名
   * </pre>
   *
   * <code>string formName = 2;</code>
   * @return The bytes for formName.
   */
  com.google.protobuf.ByteString
      getFormNameBytes();

  /**
   * <pre>
   * 专业组信息
   * </pre>
   *
   * <code>.FormDetailInfo detail = 3;</code>
   * @return Whether the detail field is set.
   */
  boolean hasDetail();
  /**
   * <pre>
   * 专业组信息
   * </pre>
   *
   * <code>.FormDetailInfo detail = 3;</code>
   * @return The detail.
   */
  com.msg.FormDetailInfo getDetail();
  /**
   * <pre>
   * 专业组信息
   * </pre>
   *
   * <code>.FormDetailInfo detail = 3;</code>
   */
  com.msg.FormDetailInfoOrBuilder getDetailOrBuilder();

  /**
   * <pre>
   *当前登录老师的 UsersRes.id  // OrderInfo orderInfo = 1;    //
   * </pre>
   *
   * <code>int64 teacherId = 4;</code>
   * @return The teacherId.
   */
  long getTeacherId();

  /**
   * <pre>
   *志愿年份
   * </pre>
   *
   * <code>string examYear = 5;</code>
   * @return The examYear.
   */
  java.lang.String getExamYear();
  /**
   * <pre>
   *志愿年份
   * </pre>
   *
   * <code>string examYear = 5;</code>
   * @return The bytes for examYear.
   */
  com.google.protobuf.ByteString
      getExamYearBytes();
}
