// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: yzpm.proto

package com.msg;

public interface FormInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FormInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *志愿表唯一id
   * </pre>
   *
   * <code>fixed64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <pre>
   *fixed64 orderId = 2;          //关联的客单id
   * </pre>
   *
   * <code>int64 lastUpdateDate = 3;</code>
   * @return The lastUpdateDate.
   */
  long getLastUpdateDate();

  /**
   * <pre>
   *志愿表名
   * </pre>
   *
   * <code>string formName = 4;</code>
   * @return The formName.
   */
  java.lang.String getFormName();
  /**
   * <pre>
   *志愿表名
   * </pre>
   *
   * <code>string formName = 4;</code>
   * @return The bytes for formName.
   */
  com.google.protobuf.ByteString
      getFormNameBytes();

  /**
   * <pre>
   *科目
   * </pre>
   *
   * <code>repeated string examSubject = 5;</code>
   * @return A list containing the examSubject.
   */
  java.util.List<java.lang.String>
      getExamSubjectList();
  /**
   * <pre>
   *科目
   * </pre>
   *
   * <code>repeated string examSubject = 5;</code>
   * @return The count of examSubject.
   */
  int getExamSubjectCount();
  /**
   * <pre>
   *科目
   * </pre>
   *
   * <code>repeated string examSubject = 5;</code>
   * @param index The index of the element to return.
   * @return The examSubject at the given index.
   */
  java.lang.String getExamSubject(int index);
  /**
   * <pre>
   *科目
   * </pre>
   *
   * <code>repeated string examSubject = 5;</code>
   * @param index The index of the value to return.
   * @return The bytes of the examSubject at the given index.
   */
  com.google.protobuf.ByteString
      getExamSubjectBytes(int index);

  /**
   * <pre>
   *位次
   * </pre>
   *
   * <code>string rank = 6;</code>
   * @return The rank.
   */
  java.lang.String getRank();
  /**
   * <pre>
   *位次
   * </pre>
   *
   * <code>string rank = 6;</code>
   * @return The bytes for rank.
   */
  com.google.protobuf.ByteString
      getRankBytes();

  /**
   * <pre>
   *分数
   * </pre>
   *
   * <code>string examScore = 7;</code>
   * @return The examScore.
   */
  java.lang.String getExamScore();
  /**
   * <pre>
   *分数
   * </pre>
   *
   * <code>string examScore = 7;</code>
   * @return The bytes for examScore.
   */
  com.google.protobuf.ByteString
      getExamScoreBytes();

  /**
   * <pre>
   *创建人
   * </pre>
   *
   * <code>string creator = 8;</code>
   * @return The creator.
   */
  java.lang.String getCreator();
  /**
   * <pre>
   *创建人
   * </pre>
   *
   * <code>string creator = 8;</code>
   * @return The bytes for creator.
   */
  com.google.protobuf.ByteString
      getCreatorBytes();

  /**
   * <pre>
   *string formDetail = 9;          //志愿详情 maj1_HistDBID,maj2__HistDBID|maj1__HistDBID,maj2__HistDBID
   * string selectedMajorId = 10;          //已经选择的majorids =  id,id,id
   * </pre>
   *
   * <code>int32 pici = 11;</code>
   * @return The pici.
   */
  int getPici();

  /**
   * <pre>
   *1: 已经删除; 0: 没有删除
   * </pre>
   *
   * <code>int32 isDelete = 12;</code>
   * @return The isDelete.
   */
  int getIsDelete();

  /**
   * <pre>
   *状态:0:未锁定  1:锁定
   * </pre>
   *
   * <code>int32 status = 13;</code>
   * @return The status.
   */
  int getStatus();

  /**
   * <pre>
   *锁定form的用户id
   * </pre>
   *
   * <code>fixed64 lockerId = 14;</code>
   * @return The lockerId.
   */
  long getLockerId();

  /**
   * <pre>
   *锁定form的用户 角色类型
   * </pre>
   *
   * <code>int32 lockerRole = 15;</code>
   * @return The lockerRole.
   */
  int getLockerRole();

  /**
   * <pre>
   *志愿年份
   * </pre>
   *
   * <code>string examYear = 16;</code>
   * @return The examYear.
   */
  java.lang.String getExamYear();
  /**
   * <pre>
   *志愿年份
   * </pre>
   *
   * <code>string examYear = 16;</code>
   * @return The bytes for examYear.
   */
  com.google.protobuf.ByteString
      getExamYearBytes();
}
