// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: yzpm.proto

package com.msg;

/**
 * <pre>
 *专业分类信息 第1大类
 * </pre>
 *
 * Protobuf type {@code Major1stClsInfo}
 */
public  final class Major1stClsInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Major1stClsInfo)
    Major1stClsInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Major1stClsInfo.newBuilder() to construct.
  private Major1stClsInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Major1stClsInfo() {
    major2NdClsInfo_ = java.util.Collections.emptyList();
    name_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Major1stClsInfo();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Major1stClsInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              major2NdClsInfo_ = new java.util.ArrayList<com.msg.Major2ndClsInfo>();
              mutable_bitField0_ |= 0x00000001;
            }
            major2NdClsInfo_.add(
                input.readMessage(com.msg.Major2ndClsInfo.parser(), extensionRegistry));
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        major2NdClsInfo_ = java.util.Collections.unmodifiableList(major2NdClsInfo_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.msg.YZPM.internal_static_Major1stClsInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.msg.YZPM.internal_static_Major1stClsInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.msg.Major1stClsInfo.class, com.msg.Major1stClsInfo.Builder.class);
  }

  public static final int MAJOR2NDCLSINFO_FIELD_NUMBER = 1;
  private java.util.List<com.msg.Major2ndClsInfo> major2NdClsInfo_;
  /**
   * <code>repeated .Major2ndClsInfo major2ndClsInfo = 1;</code>
   */
  public java.util.List<com.msg.Major2ndClsInfo> getMajor2NdClsInfoList() {
    return major2NdClsInfo_;
  }
  /**
   * <code>repeated .Major2ndClsInfo major2ndClsInfo = 1;</code>
   */
  public java.util.List<? extends com.msg.Major2ndClsInfoOrBuilder> 
      getMajor2NdClsInfoOrBuilderList() {
    return major2NdClsInfo_;
  }
  /**
   * <code>repeated .Major2ndClsInfo major2ndClsInfo = 1;</code>
   */
  public int getMajor2NdClsInfoCount() {
    return major2NdClsInfo_.size();
  }
  /**
   * <code>repeated .Major2ndClsInfo major2ndClsInfo = 1;</code>
   */
  public com.msg.Major2ndClsInfo getMajor2NdClsInfo(int index) {
    return major2NdClsInfo_.get(index);
  }
  /**
   * <code>repeated .Major2ndClsInfo major2ndClsInfo = 1;</code>
   */
  public com.msg.Major2ndClsInfoOrBuilder getMajor2NdClsInfoOrBuilder(
      int index) {
    return major2NdClsInfo_.get(index);
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <pre>
   *大类名
   * </pre>
   *
   * <code>string name = 2;</code>
   * @return The name.
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *大类名
   * </pre>
   *
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < major2NdClsInfo_.size(); i++) {
      output.writeMessage(1, major2NdClsInfo_.get(i));
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < major2NdClsInfo_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, major2NdClsInfo_.get(i));
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.msg.Major1stClsInfo)) {
      return super.equals(obj);
    }
    com.msg.Major1stClsInfo other = (com.msg.Major1stClsInfo) obj;

    if (!getMajor2NdClsInfoList()
        .equals(other.getMajor2NdClsInfoList())) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getMajor2NdClsInfoCount() > 0) {
      hash = (37 * hash) + MAJOR2NDCLSINFO_FIELD_NUMBER;
      hash = (53 * hash) + getMajor2NdClsInfoList().hashCode();
    }
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.msg.Major1stClsInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.msg.Major1stClsInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.msg.Major1stClsInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.msg.Major1stClsInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.msg.Major1stClsInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.msg.Major1stClsInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.msg.Major1stClsInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.msg.Major1stClsInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.msg.Major1stClsInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.msg.Major1stClsInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.msg.Major1stClsInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.msg.Major1stClsInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.msg.Major1stClsInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *专业分类信息 第1大类
   * </pre>
   *
   * Protobuf type {@code Major1stClsInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Major1stClsInfo)
      com.msg.Major1stClsInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.msg.YZPM.internal_static_Major1stClsInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.msg.YZPM.internal_static_Major1stClsInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.msg.Major1stClsInfo.class, com.msg.Major1stClsInfo.Builder.class);
    }

    // Construct using com.msg.Major1stClsInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getMajor2NdClsInfoFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (major2NdClsInfoBuilder_ == null) {
        major2NdClsInfo_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        major2NdClsInfoBuilder_.clear();
      }
      name_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.msg.YZPM.internal_static_Major1stClsInfo_descriptor;
    }

    @java.lang.Override
    public com.msg.Major1stClsInfo getDefaultInstanceForType() {
      return com.msg.Major1stClsInfo.getDefaultInstance();
    }

    @java.lang.Override
    public com.msg.Major1stClsInfo build() {
      com.msg.Major1stClsInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.msg.Major1stClsInfo buildPartial() {
      com.msg.Major1stClsInfo result = new com.msg.Major1stClsInfo(this);
      int from_bitField0_ = bitField0_;
      if (major2NdClsInfoBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          major2NdClsInfo_ = java.util.Collections.unmodifiableList(major2NdClsInfo_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.major2NdClsInfo_ = major2NdClsInfo_;
      } else {
        result.major2NdClsInfo_ = major2NdClsInfoBuilder_.build();
      }
      result.name_ = name_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.msg.Major1stClsInfo) {
        return mergeFrom((com.msg.Major1stClsInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.msg.Major1stClsInfo other) {
      if (other == com.msg.Major1stClsInfo.getDefaultInstance()) return this;
      if (major2NdClsInfoBuilder_ == null) {
        if (!other.major2NdClsInfo_.isEmpty()) {
          if (major2NdClsInfo_.isEmpty()) {
            major2NdClsInfo_ = other.major2NdClsInfo_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureMajor2NdClsInfoIsMutable();
            major2NdClsInfo_.addAll(other.major2NdClsInfo_);
          }
          onChanged();
        }
      } else {
        if (!other.major2NdClsInfo_.isEmpty()) {
          if (major2NdClsInfoBuilder_.isEmpty()) {
            major2NdClsInfoBuilder_.dispose();
            major2NdClsInfoBuilder_ = null;
            major2NdClsInfo_ = other.major2NdClsInfo_;
            bitField0_ = (bitField0_ & ~0x00000001);
            major2NdClsInfoBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getMajor2NdClsInfoFieldBuilder() : null;
          } else {
            major2NdClsInfoBuilder_.addAllMessages(other.major2NdClsInfo_);
          }
        }
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.msg.Major1stClsInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.msg.Major1stClsInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.msg.Major2ndClsInfo> major2NdClsInfo_ =
      java.util.Collections.emptyList();
    private void ensureMajor2NdClsInfoIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        major2NdClsInfo_ = new java.util.ArrayList<com.msg.Major2ndClsInfo>(major2NdClsInfo_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.msg.Major2ndClsInfo, com.msg.Major2ndClsInfo.Builder, com.msg.Major2ndClsInfoOrBuilder> major2NdClsInfoBuilder_;

    /**
     * <code>repeated .Major2ndClsInfo major2ndClsInfo = 1;</code>
     */
    public java.util.List<com.msg.Major2ndClsInfo> getMajor2NdClsInfoList() {
      if (major2NdClsInfoBuilder_ == null) {
        return java.util.Collections.unmodifiableList(major2NdClsInfo_);
      } else {
        return major2NdClsInfoBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Major2ndClsInfo major2ndClsInfo = 1;</code>
     */
    public int getMajor2NdClsInfoCount() {
      if (major2NdClsInfoBuilder_ == null) {
        return major2NdClsInfo_.size();
      } else {
        return major2NdClsInfoBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Major2ndClsInfo major2ndClsInfo = 1;</code>
     */
    public com.msg.Major2ndClsInfo getMajor2NdClsInfo(int index) {
      if (major2NdClsInfoBuilder_ == null) {
        return major2NdClsInfo_.get(index);
      } else {
        return major2NdClsInfoBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Major2ndClsInfo major2ndClsInfo = 1;</code>
     */
    public Builder setMajor2NdClsInfo(
        int index, com.msg.Major2ndClsInfo value) {
      if (major2NdClsInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMajor2NdClsInfoIsMutable();
        major2NdClsInfo_.set(index, value);
        onChanged();
      } else {
        major2NdClsInfoBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Major2ndClsInfo major2ndClsInfo = 1;</code>
     */
    public Builder setMajor2NdClsInfo(
        int index, com.msg.Major2ndClsInfo.Builder builderForValue) {
      if (major2NdClsInfoBuilder_ == null) {
        ensureMajor2NdClsInfoIsMutable();
        major2NdClsInfo_.set(index, builderForValue.build());
        onChanged();
      } else {
        major2NdClsInfoBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Major2ndClsInfo major2ndClsInfo = 1;</code>
     */
    public Builder addMajor2NdClsInfo(com.msg.Major2ndClsInfo value) {
      if (major2NdClsInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMajor2NdClsInfoIsMutable();
        major2NdClsInfo_.add(value);
        onChanged();
      } else {
        major2NdClsInfoBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Major2ndClsInfo major2ndClsInfo = 1;</code>
     */
    public Builder addMajor2NdClsInfo(
        int index, com.msg.Major2ndClsInfo value) {
      if (major2NdClsInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMajor2NdClsInfoIsMutable();
        major2NdClsInfo_.add(index, value);
        onChanged();
      } else {
        major2NdClsInfoBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Major2ndClsInfo major2ndClsInfo = 1;</code>
     */
    public Builder addMajor2NdClsInfo(
        com.msg.Major2ndClsInfo.Builder builderForValue) {
      if (major2NdClsInfoBuilder_ == null) {
        ensureMajor2NdClsInfoIsMutable();
        major2NdClsInfo_.add(builderForValue.build());
        onChanged();
      } else {
        major2NdClsInfoBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Major2ndClsInfo major2ndClsInfo = 1;</code>
     */
    public Builder addMajor2NdClsInfo(
        int index, com.msg.Major2ndClsInfo.Builder builderForValue) {
      if (major2NdClsInfoBuilder_ == null) {
        ensureMajor2NdClsInfoIsMutable();
        major2NdClsInfo_.add(index, builderForValue.build());
        onChanged();
      } else {
        major2NdClsInfoBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Major2ndClsInfo major2ndClsInfo = 1;</code>
     */
    public Builder addAllMajor2NdClsInfo(
        java.lang.Iterable<? extends com.msg.Major2ndClsInfo> values) {
      if (major2NdClsInfoBuilder_ == null) {
        ensureMajor2NdClsInfoIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, major2NdClsInfo_);
        onChanged();
      } else {
        major2NdClsInfoBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Major2ndClsInfo major2ndClsInfo = 1;</code>
     */
    public Builder clearMajor2NdClsInfo() {
      if (major2NdClsInfoBuilder_ == null) {
        major2NdClsInfo_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        major2NdClsInfoBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Major2ndClsInfo major2ndClsInfo = 1;</code>
     */
    public Builder removeMajor2NdClsInfo(int index) {
      if (major2NdClsInfoBuilder_ == null) {
        ensureMajor2NdClsInfoIsMutable();
        major2NdClsInfo_.remove(index);
        onChanged();
      } else {
        major2NdClsInfoBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Major2ndClsInfo major2ndClsInfo = 1;</code>
     */
    public com.msg.Major2ndClsInfo.Builder getMajor2NdClsInfoBuilder(
        int index) {
      return getMajor2NdClsInfoFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Major2ndClsInfo major2ndClsInfo = 1;</code>
     */
    public com.msg.Major2ndClsInfoOrBuilder getMajor2NdClsInfoOrBuilder(
        int index) {
      if (major2NdClsInfoBuilder_ == null) {
        return major2NdClsInfo_.get(index);  } else {
        return major2NdClsInfoBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Major2ndClsInfo major2ndClsInfo = 1;</code>
     */
    public java.util.List<? extends com.msg.Major2ndClsInfoOrBuilder> 
         getMajor2NdClsInfoOrBuilderList() {
      if (major2NdClsInfoBuilder_ != null) {
        return major2NdClsInfoBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(major2NdClsInfo_);
      }
    }
    /**
     * <code>repeated .Major2ndClsInfo major2ndClsInfo = 1;</code>
     */
    public com.msg.Major2ndClsInfo.Builder addMajor2NdClsInfoBuilder() {
      return getMajor2NdClsInfoFieldBuilder().addBuilder(
          com.msg.Major2ndClsInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .Major2ndClsInfo major2ndClsInfo = 1;</code>
     */
    public com.msg.Major2ndClsInfo.Builder addMajor2NdClsInfoBuilder(
        int index) {
      return getMajor2NdClsInfoFieldBuilder().addBuilder(
          index, com.msg.Major2ndClsInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .Major2ndClsInfo major2ndClsInfo = 1;</code>
     */
    public java.util.List<com.msg.Major2ndClsInfo.Builder> 
         getMajor2NdClsInfoBuilderList() {
      return getMajor2NdClsInfoFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.msg.Major2ndClsInfo, com.msg.Major2ndClsInfo.Builder, com.msg.Major2ndClsInfoOrBuilder> 
        getMajor2NdClsInfoFieldBuilder() {
      if (major2NdClsInfoBuilder_ == null) {
        major2NdClsInfoBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.msg.Major2ndClsInfo, com.msg.Major2ndClsInfo.Builder, com.msg.Major2ndClsInfoOrBuilder>(
                major2NdClsInfo_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        major2NdClsInfo_ = null;
      }
      return major2NdClsInfoBuilder_;
    }

    private java.lang.Object name_ = "";
    /**
     * <pre>
     *大类名
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *大类名
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *大类名
     * </pre>
     *
     * <code>string name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *大类名
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *大类名
     * </pre>
     *
     * <code>string name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Major1stClsInfo)
  }

  // @@protoc_insertion_point(class_scope:Major1stClsInfo)
  private static final com.msg.Major1stClsInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.msg.Major1stClsInfo();
  }

  public static com.msg.Major1stClsInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Major1stClsInfo>
      PARSER = new com.google.protobuf.AbstractParser<Major1stClsInfo>() {
    @java.lang.Override
    public Major1stClsInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Major1stClsInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Major1stClsInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Major1stClsInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.msg.Major1stClsInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

