// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: yzpm.proto

package com.msg;

public interface MajorInfoYearOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MajorInfoYear)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *id
   * </pre>
   *
   * <code>fixed64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <pre>
   *院校专业组代码
   * </pre>
   *
   * <code>string uniMajorCode = 2;</code>
   * @return The uniMajorCode.
   */
  java.lang.String getUniMajorCode();
  /**
   * <pre>
   *院校专业组代码
   * </pre>
   *
   * <code>string uniMajorCode = 2;</code>
   * @return The bytes for uniMajorCode.
   */
  com.google.protobuf.ByteString
      getUniMajorCodeBytes();

  /**
   * <pre>
   *批次: 1: 本科A,2:本科B, 3: 提前批本A, 4:提前批本B
   * </pre>
   *
   * <code>int32 pici = 3;</code>
   * @return The pici.
   */
  int getPici();

  /**
   * <pre>
   *院校名称
   * </pre>
   *
   * <code>string schoolName = 4;</code>
   * @return The schoolName.
   */
  java.lang.String getSchoolName();
  /**
   * <pre>
   *院校名称
   * </pre>
   *
   * <code>string schoolName = 4;</code>
   * @return The bytes for schoolName.
   */
  com.google.protobuf.ByteString
      getSchoolNameBytes();

  /**
   * <pre>
   *科目要求
   * </pre>
   *
   * <code>string subjectRequirement = 5;</code>
   * @return The subjectRequirement.
   */
  java.lang.String getSubjectRequirement();
  /**
   * <pre>
   *科目要求
   * </pre>
   *
   * <code>string subjectRequirement = 5;</code>
   * @return The bytes for subjectRequirement.
   */
  com.google.protobuf.ByteString
      getSubjectRequirementBytes();

  /**
   * <pre>
   *22组分数
   * </pre>
   *
   * <code>string scoreFor22 = 6;</code>
   * @return The scoreFor22.
   */
  java.lang.String getScoreFor22();
  /**
   * <pre>
   *22组分数
   * </pre>
   *
   * <code>string scoreFor22 = 6;</code>
   * @return The bytes for scoreFor22.
   */
  com.google.protobuf.ByteString
      getScoreFor22Bytes();

  /**
   * <pre>
   *22组位次
   * </pre>
   *
   * <code>string rankFor22 = 7;</code>
   * @return The rankFor22.
   */
  java.lang.String getRankFor22();
  /**
   * <pre>
   *22组位次
   * </pre>
   *
   * <code>string rankFor22 = 7;</code>
   * @return The bytes for rankFor22.
   */
  com.google.protobuf.ByteString
      getRankFor22Bytes();

  /**
   * <pre>
   *专业代码
   * </pre>
   *
   * <code>string majorCode = 8;</code>
   * @return The majorCode.
   */
  java.lang.String getMajorCode();
  /**
   * <pre>
   *专业代码
   * </pre>
   *
   * <code>string majorCode = 8;</code>
   * @return The bytes for majorCode.
   */
  com.google.protobuf.ByteString
      getMajorCodeBytes();

  /**
   * <pre>
   *专业名称
   * </pre>
   *
   * <code>string majorName = 9;</code>
   * @return The majorName.
   */
  java.lang.String getMajorName();
  /**
   * <pre>
   *专业名称
   * </pre>
   *
   * <code>string majorName = 9;</code>
   * @return The bytes for majorName.
   */
  com.google.protobuf.ByteString
      getMajorNameBytes();

  /**
   * <pre>
   *专业备注
   * </pre>
   *
   * <code>string majorComments = 10;</code>
   * @return The majorComments.
   */
  java.lang.String getMajorComments();
  /**
   * <pre>
   *专业备注
   * </pre>
   *
   * <code>string majorComments = 10;</code>
   * @return The bytes for majorComments.
   */
  com.google.protobuf.ByteString
      getMajorCommentsBytes();

  /**
   * <pre>
   *外语语种
   * </pre>
   *
   * <code>string requireLang = 11;</code>
   * @return The requireLang.
   */
  java.lang.String getRequireLang();
  /**
   * <pre>
   *外语语种
   * </pre>
   *
   * <code>string requireLang = 11;</code>
   * @return The bytes for requireLang.
   */
  com.google.protobuf.ByteString
      getRequireLangBytes();

  /**
   * <pre>
   *是否口试
   * </pre>
   *
   * <code>string requireInterview = 12;</code>
   * @return The requireInterview.
   */
  java.lang.String getRequireInterview();
  /**
   * <pre>
   *是否口试
   * </pre>
   *
   * <code>string requireInterview = 12;</code>
   * @return The bytes for requireInterview.
   */
  com.google.protobuf.ByteString
      getRequireInterviewBytes();

  /**
   * <pre>
   *学制
   * </pre>
   *
   * <code>string majorDuration = 13;</code>
   * @return The majorDuration.
   */
  java.lang.String getMajorDuration();
  /**
   * <pre>
   *学制
   * </pre>
   *
   * <code>string majorDuration = 13;</code>
   * @return The bytes for majorDuration.
   */
  com.google.protobuf.ByteString
      getMajorDurationBytes();

  /**
   * <pre>
   *收费标准
   * </pre>
   *
   * <code>string majorTuition = 14;</code>
   * @return The majorTuition.
   */
  java.lang.String getMajorTuition();
  /**
   * <pre>
   *收费标准
   * </pre>
   *
   * <code>string majorTuition = 14;</code>
   * @return The bytes for majorTuition.
   */
  com.google.protobuf.ByteString
      getMajorTuitionBytes();

  /**
   * <pre>
   *22年计划数
   * </pre>
   *
   * <code>string major22Plan = 15;</code>
   * @return The major22Plan.
   */
  java.lang.String getMajor22Plan();
  /**
   * <pre>
   *22年计划数
   * </pre>
   *
   * <code>string major22Plan = 15;</code>
   * @return The bytes for major22Plan.
   */
  com.google.protobuf.ByteString
      getMajor22PlanBytes();

  /**
   * <pre>
   *22录取数
   * </pre>
   *
   * <code>string major22Admin = 16;</code>
   * @return The major22Admin.
   */
  java.lang.String getMajor22Admin();
  /**
   * <pre>
   *22录取数
   * </pre>
   *
   * <code>string major22Admin = 16;</code>
   * @return The bytes for major22Admin.
   */
  com.google.protobuf.ByteString
      getMajor22AdminBytes();

  /**
   * <pre>
   *22年低
   * </pre>
   *
   * <code>string major22LowScore = 17;</code>
   * @return The major22LowScore.
   */
  java.lang.String getMajor22LowScore();
  /**
   * <pre>
   *22年低
   * </pre>
   *
   * <code>string major22LowScore = 17;</code>
   * @return The bytes for major22LowScore.
   */
  com.google.protobuf.ByteString
      getMajor22LowScoreBytes();

  /**
   * <pre>
   *22年低位次
   * </pre>
   *
   * <code>string major22LowRank = 18;</code>
   * @return The major22LowRank.
   */
  java.lang.String getMajor22LowRank();
  /**
   * <pre>
   *22年低位次
   * </pre>
   *
   * <code>string major22LowRank = 18;</code>
   * @return The bytes for major22LowRank.
   */
  com.google.protobuf.ByteString
      getMajor22LowRankBytes();

  /**
   * <pre>
   *22年高分
   * </pre>
   *
   * <code>string major22HScore = 19;</code>
   * @return The major22HScore.
   */
  java.lang.String getMajor22HScore();
  /**
   * <pre>
   *22年高分
   * </pre>
   *
   * <code>string major22HScore = 19;</code>
   * @return The bytes for major22HScore.
   */
  com.google.protobuf.ByteString
      getMajor22HScoreBytes();

  /**
   * <pre>
   *22年高位次
   * </pre>
   *
   * <code>string major22HRank = 20;</code>
   * @return The major22HRank.
   */
  java.lang.String getMajor22HRank();
  /**
   * <pre>
   *22年高位次
   * </pre>
   *
   * <code>string major22HRank = 20;</code>
   * @return The bytes for major22HRank.
   */
  com.google.protobuf.ByteString
      getMajor22HRankBytes();

  /**
   * <pre>
   *22年平分
   * </pre>
   *
   * <code>string major22AvgScore = 21;</code>
   * @return The major22AvgScore.
   */
  java.lang.String getMajor22AvgScore();
  /**
   * <pre>
   *22年平分
   * </pre>
   *
   * <code>string major22AvgScore = 21;</code>
   * @return The bytes for major22AvgScore.
   */
  com.google.protobuf.ByteString
      getMajor22AvgScoreBytes();

  /**
   * <pre>
   *22年平位次
   * </pre>
   *
   * <code>string major22AvgRank = 22;</code>
   * @return The major22AvgRank.
   */
  java.lang.String getMajor22AvgRank();
  /**
   * <pre>
   *22年平位次
   * </pre>
   *
   * <code>string major22AvgRank = 22;</code>
   * @return The bytes for major22AvgRank.
   */
  com.google.protobuf.ByteString
      getMajor22AvgRankBytes();

  /**
   * <pre>
   *计划批次
   * </pre>
   *
   * <code>string piciName = 23;</code>
   * @return The piciName.
   */
  java.lang.String getPiciName();
  /**
   * <pre>
   *计划批次
   * </pre>
   *
   * <code>string piciName = 23;</code>
   * @return The bytes for piciName.
   */
  com.google.protobuf.ByteString
      getPiciNameBytes();
}
