// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: yzpm.proto

package com.msg;

public interface S_CreateFormInfo_5003OrBuilder extends
    // @@protoc_insertion_point(interface_extends:S_CreateFormInfo_5003)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *返回消息体
   * </pre>
   *
   * <code>.MsgResult result = 1;</code>
   * @return Whether the result field is set.
   */
  boolean hasResult();
  /**
   * <pre>
   *返回消息体
   * </pre>
   *
   * <code>.MsgResult result = 1;</code>
   * @return The result.
   */
  com.msg.MsgResult getResult();
  /**
   * <pre>
   *返回消息体
   * </pre>
   *
   * <code>.MsgResult result = 1;</code>
   */
  com.msg.MsgResultOrBuilder getResultOrBuilder();

  /**
   * <pre>
   *志愿表信息
   * </pre>
   *
   * <code>.FormInfo formInfo = 2;</code>
   * @return Whether the formInfo field is set.
   */
  boolean hasFormInfo();
  /**
   * <pre>
   *志愿表信息
   * </pre>
   *
   * <code>.FormInfo formInfo = 2;</code>
   * @return The formInfo.
   */
  com.msg.FormInfo getFormInfo();
  /**
   * <pre>
   *志愿表信息
   * </pre>
   *
   * <code>.FormInfo formInfo = 2;</code>
   */
  com.msg.FormInfoOrBuilder getFormInfoOrBuilder();
}
