// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: yzpm.proto

package com.msg;

public interface S_GetAllMajorsOfUni_4005OrBuilder extends
    // @@protoc_insertion_point(interface_extends:S_GetAllMajorsOfUni_4005)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *返回消息体
   * </pre>
   *
   * <code>.MsgResult result = 1;</code>
   * @return Whether the result field is set.
   */
  boolean hasResult();
  /**
   * <pre>
   *返回消息体
   * </pre>
   *
   * <code>.MsgResult result = 1;</code>
   * @return The result.
   */
  com.msg.MsgResult getResult();
  /**
   * <pre>
   *返回消息体
   * </pre>
   *
   * <code>.MsgResult result = 1;</code>
   */
  com.msg.MsgResultOrBuilder getResultOrBuilder();

  /**
   * <pre>
   *最近3年依次为: 2022, 2021,2020
   * </pre>
   *
   * <code>repeated string latest3Year = 2;</code>
   * @return A list containing the latest3Year.
   */
  java.util.List<java.lang.String>
      getLatest3YearList();
  /**
   * <pre>
   *最近3年依次为: 2022, 2021,2020
   * </pre>
   *
   * <code>repeated string latest3Year = 2;</code>
   * @return The count of latest3Year.
   */
  int getLatest3YearCount();
  /**
   * <pre>
   *最近3年依次为: 2022, 2021,2020
   * </pre>
   *
   * <code>repeated string latest3Year = 2;</code>
   * @param index The index of the element to return.
   * @return The latest3Year at the given index.
   */
  java.lang.String getLatest3Year(int index);
  /**
   * <pre>
   *最近3年依次为: 2022, 2021,2020
   * </pre>
   *
   * <code>repeated string latest3Year = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the latest3Year at the given index.
   */
  com.google.protobuf.ByteString
      getLatest3YearBytes(int index);

  /**
   * <pre>
   *最近1年的信息 2022年
   * </pre>
   *
   * <code>repeated .MajorInfoYear majorInfoYear1 = 3;</code>
   */
  java.util.List<com.msg.MajorInfoYear> 
      getMajorInfoYear1List();
  /**
   * <pre>
   *最近1年的信息 2022年
   * </pre>
   *
   * <code>repeated .MajorInfoYear majorInfoYear1 = 3;</code>
   */
  com.msg.MajorInfoYear getMajorInfoYear1(int index);
  /**
   * <pre>
   *最近1年的信息 2022年
   * </pre>
   *
   * <code>repeated .MajorInfoYear majorInfoYear1 = 3;</code>
   */
  int getMajorInfoYear1Count();
  /**
   * <pre>
   *最近1年的信息 2022年
   * </pre>
   *
   * <code>repeated .MajorInfoYear majorInfoYear1 = 3;</code>
   */
  java.util.List<? extends com.msg.MajorInfoYearOrBuilder> 
      getMajorInfoYear1OrBuilderList();
  /**
   * <pre>
   *最近1年的信息 2022年
   * </pre>
   *
   * <code>repeated .MajorInfoYear majorInfoYear1 = 3;</code>
   */
  com.msg.MajorInfoYearOrBuilder getMajorInfoYear1OrBuilder(
      int index);

  /**
   * <pre>
   *最近2年 2021年
   * </pre>
   *
   * <code>repeated .MajorInfoYear majorInfoYear2 = 4;</code>
   */
  java.util.List<com.msg.MajorInfoYear> 
      getMajorInfoYear2List();
  /**
   * <pre>
   *最近2年 2021年
   * </pre>
   *
   * <code>repeated .MajorInfoYear majorInfoYear2 = 4;</code>
   */
  com.msg.MajorInfoYear getMajorInfoYear2(int index);
  /**
   * <pre>
   *最近2年 2021年
   * </pre>
   *
   * <code>repeated .MajorInfoYear majorInfoYear2 = 4;</code>
   */
  int getMajorInfoYear2Count();
  /**
   * <pre>
   *最近2年 2021年
   * </pre>
   *
   * <code>repeated .MajorInfoYear majorInfoYear2 = 4;</code>
   */
  java.util.List<? extends com.msg.MajorInfoYearOrBuilder> 
      getMajorInfoYear2OrBuilderList();
  /**
   * <pre>
   *最近2年 2021年
   * </pre>
   *
   * <code>repeated .MajorInfoYear majorInfoYear2 = 4;</code>
   */
  com.msg.MajorInfoYearOrBuilder getMajorInfoYear2OrBuilder(
      int index);

  /**
   * <pre>
   *最近3年
   * </pre>
   *
   * <code>repeated .MajorInfoYear majorInfoYear3 = 5;</code>
   */
  java.util.List<com.msg.MajorInfoYear> 
      getMajorInfoYear3List();
  /**
   * <pre>
   *最近3年
   * </pre>
   *
   * <code>repeated .MajorInfoYear majorInfoYear3 = 5;</code>
   */
  com.msg.MajorInfoYear getMajorInfoYear3(int index);
  /**
   * <pre>
   *最近3年
   * </pre>
   *
   * <code>repeated .MajorInfoYear majorInfoYear3 = 5;</code>
   */
  int getMajorInfoYear3Count();
  /**
   * <pre>
   *最近3年
   * </pre>
   *
   * <code>repeated .MajorInfoYear majorInfoYear3 = 5;</code>
   */
  java.util.List<? extends com.msg.MajorInfoYearOrBuilder> 
      getMajorInfoYear3OrBuilderList();
  /**
   * <pre>
   *最近3年
   * </pre>
   *
   * <code>repeated .MajorInfoYear majorInfoYear3 = 5;</code>
   */
  com.msg.MajorInfoYearOrBuilder getMajorInfoYear3OrBuilder(
      int index);
}
