// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: yzpm.proto

package com.msg;

public interface S_UpdateMajorPreference_4003OrBuilder extends
    // @@protoc_insertion_point(interface_extends:S_UpdateMajorPreference_4003)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *返回消息体
   * </pre>
   *
   * <code>.MsgResult result = 1;</code>
   * @return Whether the result field is set.
   */
  boolean hasResult();
  /**
   * <pre>
   *返回消息体
   * </pre>
   *
   * <code>.MsgResult result = 1;</code>
   * @return The result.
   */
  com.msg.MsgResult getResult();
  /**
   * <pre>
   *返回消息体
   * </pre>
   *
   * <code>.MsgResult result = 1;</code>
   */
  com.msg.MsgResultOrBuilder getResultOrBuilder();
}
