// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: yzpm.proto

package com.msg;

/**
 * <pre>
 * 志愿模板
 * </pre>
 *
 * Protobuf type {@code TemplateInfo}
 */
public  final class TemplateInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:TemplateInfo)
    TemplateInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TemplateInfo.newBuilder() to construct.
  private TemplateInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TemplateInfo() {
    templateName_ = "";
    creatorName_ = "";
    authorTeacherIds_ = emptyLongList();
    examYear_ = "";
    favoredMajorCls1List_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TemplateInfo();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TemplateInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 9: {

            id_ = input.readFixed64();
            break;
          }
          case 16: {

            lastUpdateDate_ = input.readInt64();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            templateName_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            creatorName_ = s;
            break;
          }
          case 41: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              authorTeacherIds_ = newLongList();
              mutable_bitField0_ |= 0x00000001;
            }
            authorTeacherIds_.addLong(input.readFixed64());
            break;
          }
          case 42: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
              authorTeacherIds_ = newLongList();
              mutable_bitField0_ |= 0x00000001;
            }
            while (input.getBytesUntilLimit() > 0) {
              authorTeacherIds_.addLong(input.readFixed64());
            }
            input.popLimit(limit);
            break;
          }
          case 48: {

            isPublic_ = input.readInt32();
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            examYear_ = s;
            break;
          }
          case 64: {

            pici_ = input.readInt32();
            break;
          }
          case 72: {

            isDelete_ = input.readInt32();
            break;
          }
          case 80: {

            creatorId_ = input.readInt64();
            break;
          }
          case 90: {
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              favoredMajorCls1List_ = new java.util.ArrayList<com.msg.Major1stClsInfo>();
              mutable_bitField0_ |= 0x00000002;
            }
            favoredMajorCls1List_.add(
                input.readMessage(com.msg.Major1stClsInfo.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        authorTeacherIds_.makeImmutable(); // C
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        favoredMajorCls1List_ = java.util.Collections.unmodifiableList(favoredMajorCls1List_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.msg.YZPM.internal_static_TemplateInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.msg.YZPM.internal_static_TemplateInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.msg.TemplateInfo.class, com.msg.TemplateInfo.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private long id_;
  /**
   * <pre>
   *志愿表唯一id
   * </pre>
   *
   * <code>fixed64 id = 1;</code>
   * @return The id.
   */
  public long getId() {
    return id_;
  }

  public static final int LASTUPDATEDATE_FIELD_NUMBER = 2;
  private long lastUpdateDate_;
  /**
   * <pre>
   *最后编辑时间
   * </pre>
   *
   * <code>int64 lastUpdateDate = 2;</code>
   * @return The lastUpdateDate.
   */
  public long getLastUpdateDate() {
    return lastUpdateDate_;
  }

  public static final int TEMPLATENAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object templateName_;
  /**
   * <pre>
   *模板名 不能重名
   * </pre>
   *
   * <code>string templateName = 3;</code>
   * @return The templateName.
   */
  public java.lang.String getTemplateName() {
    java.lang.Object ref = templateName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      templateName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *模板名 不能重名
   * </pre>
   *
   * <code>string templateName = 3;</code>
   * @return The bytes for templateName.
   */
  public com.google.protobuf.ByteString
      getTemplateNameBytes() {
    java.lang.Object ref = templateName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      templateName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CREATORNAME_FIELD_NUMBER = 4;
  private volatile java.lang.Object creatorName_;
  /**
   * <pre>
   *创建人
   * </pre>
   *
   * <code>string creatorName = 4;</code>
   * @return The creatorName.
   */
  public java.lang.String getCreatorName() {
    java.lang.Object ref = creatorName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      creatorName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *创建人
   * </pre>
   *
   * <code>string creatorName = 4;</code>
   * @return The bytes for creatorName.
   */
  public com.google.protobuf.ByteString
      getCreatorNameBytes() {
    java.lang.Object ref = creatorName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      creatorName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AUTHORTEACHERIDS_FIELD_NUMBER = 5;
  private com.google.protobuf.Internal.LongList authorTeacherIds_;
  /**
   * <pre>
   *授权可查看的老师Ids [(id),(id),(id)]
   * </pre>
   *
   * <code>repeated fixed64 authorTeacherIds = 5;</code>
   * @return A list containing the authorTeacherIds.
   */
  public java.util.List<java.lang.Long>
      getAuthorTeacherIdsList() {
    return authorTeacherIds_;
  }
  /**
   * <pre>
   *授权可查看的老师Ids [(id),(id),(id)]
   * </pre>
   *
   * <code>repeated fixed64 authorTeacherIds = 5;</code>
   * @return The count of authorTeacherIds.
   */
  public int getAuthorTeacherIdsCount() {
    return authorTeacherIds_.size();
  }
  /**
   * <pre>
   *授权可查看的老师Ids [(id),(id),(id)]
   * </pre>
   *
   * <code>repeated fixed64 authorTeacherIds = 5;</code>
   * @param index The index of the element to return.
   * @return The authorTeacherIds at the given index.
   */
  public long getAuthorTeacherIds(int index) {
    return authorTeacherIds_.getLong(index);
  }
  private int authorTeacherIdsMemoizedSerializedSize = -1;

  public static final int ISPUBLIC_FIELD_NUMBER = 6;
  private int isPublic_;
  /**
   * <pre>
   *1: 公开; 0: 没有公开
   * </pre>
   *
   * <code>int32 isPublic = 6;</code>
   * @return The isPublic.
   */
  public int getIsPublic() {
    return isPublic_;
  }

  public static final int EXAMYEAR_FIELD_NUMBER = 7;
  private volatile java.lang.Object examYear_;
  /**
   * <pre>
   *志愿年份
   * </pre>
   *
   * <code>string examYear = 7;</code>
   * @return The examYear.
   */
  public java.lang.String getExamYear() {
    java.lang.Object ref = examYear_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      examYear_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *志愿年份
   * </pre>
   *
   * <code>string examYear = 7;</code>
   * @return The bytes for examYear.
   */
  public com.google.protobuf.ByteString
      getExamYearBytes() {
    java.lang.Object ref = examYear_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      examYear_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PICI_FIELD_NUMBER = 8;
  private int pici_;
  /**
   * <pre>
   *批次: 1: 本科A,2:本科B, 3: 提前批本A, 4:提前批本B
   * </pre>
   *
   * <code>int32 pici = 8;</code>
   * @return The pici.
   */
  public int getPici() {
    return pici_;
  }

  public static final int ISDELETE_FIELD_NUMBER = 9;
  private int isDelete_;
  /**
   * <pre>
   *1: 已经删除; 0: 没有删除
   * </pre>
   *
   * <code>int32 isDelete = 9;</code>
   * @return The isDelete.
   */
  public int getIsDelete() {
    return isDelete_;
  }

  public static final int CREATORID_FIELD_NUMBER = 10;
  private long creatorId_;
  /**
   * <pre>
   *创建人 id
   * </pre>
   *
   * <code>int64 creatorId = 10;</code>
   * @return The creatorId.
   */
  public long getCreatorId() {
    return creatorId_;
  }

  public static final int FAVOREDMAJORCLS1LIST_FIELD_NUMBER = 11;
  private java.util.List<com.msg.Major1stClsInfo> favoredMajorCls1List_;
  /**
   * <pre>
   *模板相关的 专业信息list,
   * </pre>
   *
   * <code>repeated .Major1stClsInfo favoredMajorCls1List = 11;</code>
   */
  public java.util.List<com.msg.Major1stClsInfo> getFavoredMajorCls1ListList() {
    return favoredMajorCls1List_;
  }
  /**
   * <pre>
   *模板相关的 专业信息list,
   * </pre>
   *
   * <code>repeated .Major1stClsInfo favoredMajorCls1List = 11;</code>
   */
  public java.util.List<? extends com.msg.Major1stClsInfoOrBuilder> 
      getFavoredMajorCls1ListOrBuilderList() {
    return favoredMajorCls1List_;
  }
  /**
   * <pre>
   *模板相关的 专业信息list,
   * </pre>
   *
   * <code>repeated .Major1stClsInfo favoredMajorCls1List = 11;</code>
   */
  public int getFavoredMajorCls1ListCount() {
    return favoredMajorCls1List_.size();
  }
  /**
   * <pre>
   *模板相关的 专业信息list,
   * </pre>
   *
   * <code>repeated .Major1stClsInfo favoredMajorCls1List = 11;</code>
   */
  public com.msg.Major1stClsInfo getFavoredMajorCls1List(int index) {
    return favoredMajorCls1List_.get(index);
  }
  /**
   * <pre>
   *模板相关的 专业信息list,
   * </pre>
   *
   * <code>repeated .Major1stClsInfo favoredMajorCls1List = 11;</code>
   */
  public com.msg.Major1stClsInfoOrBuilder getFavoredMajorCls1ListOrBuilder(
      int index) {
    return favoredMajorCls1List_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (id_ != 0L) {
      output.writeFixed64(1, id_);
    }
    if (lastUpdateDate_ != 0L) {
      output.writeInt64(2, lastUpdateDate_);
    }
    if (!getTemplateNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, templateName_);
    }
    if (!getCreatorNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, creatorName_);
    }
    if (getAuthorTeacherIdsList().size() > 0) {
      output.writeUInt32NoTag(42);
      output.writeUInt32NoTag(authorTeacherIdsMemoizedSerializedSize);
    }
    for (int i = 0; i < authorTeacherIds_.size(); i++) {
      output.writeFixed64NoTag(authorTeacherIds_.getLong(i));
    }
    if (isPublic_ != 0) {
      output.writeInt32(6, isPublic_);
    }
    if (!getExamYearBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, examYear_);
    }
    if (pici_ != 0) {
      output.writeInt32(8, pici_);
    }
    if (isDelete_ != 0) {
      output.writeInt32(9, isDelete_);
    }
    if (creatorId_ != 0L) {
      output.writeInt64(10, creatorId_);
    }
    for (int i = 0; i < favoredMajorCls1List_.size(); i++) {
      output.writeMessage(11, favoredMajorCls1List_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeFixed64Size(1, id_);
    }
    if (lastUpdateDate_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, lastUpdateDate_);
    }
    if (!getTemplateNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, templateName_);
    }
    if (!getCreatorNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, creatorName_);
    }
    {
      int dataSize = 0;
      dataSize = 8 * getAuthorTeacherIdsList().size();
      size += dataSize;
      if (!getAuthorTeacherIdsList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      authorTeacherIdsMemoizedSerializedSize = dataSize;
    }
    if (isPublic_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, isPublic_);
    }
    if (!getExamYearBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, examYear_);
    }
    if (pici_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(8, pici_);
    }
    if (isDelete_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(9, isDelete_);
    }
    if (creatorId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(10, creatorId_);
    }
    for (int i = 0; i < favoredMajorCls1List_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(11, favoredMajorCls1List_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.msg.TemplateInfo)) {
      return super.equals(obj);
    }
    com.msg.TemplateInfo other = (com.msg.TemplateInfo) obj;

    if (getId()
        != other.getId()) return false;
    if (getLastUpdateDate()
        != other.getLastUpdateDate()) return false;
    if (!getTemplateName()
        .equals(other.getTemplateName())) return false;
    if (!getCreatorName()
        .equals(other.getCreatorName())) return false;
    if (!getAuthorTeacherIdsList()
        .equals(other.getAuthorTeacherIdsList())) return false;
    if (getIsPublic()
        != other.getIsPublic()) return false;
    if (!getExamYear()
        .equals(other.getExamYear())) return false;
    if (getPici()
        != other.getPici()) return false;
    if (getIsDelete()
        != other.getIsDelete()) return false;
    if (getCreatorId()
        != other.getCreatorId()) return false;
    if (!getFavoredMajorCls1ListList()
        .equals(other.getFavoredMajorCls1ListList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (37 * hash) + LASTUPDATEDATE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLastUpdateDate());
    hash = (37 * hash) + TEMPLATENAME_FIELD_NUMBER;
    hash = (53 * hash) + getTemplateName().hashCode();
    hash = (37 * hash) + CREATORNAME_FIELD_NUMBER;
    hash = (53 * hash) + getCreatorName().hashCode();
    if (getAuthorTeacherIdsCount() > 0) {
      hash = (37 * hash) + AUTHORTEACHERIDS_FIELD_NUMBER;
      hash = (53 * hash) + getAuthorTeacherIdsList().hashCode();
    }
    hash = (37 * hash) + ISPUBLIC_FIELD_NUMBER;
    hash = (53 * hash) + getIsPublic();
    hash = (37 * hash) + EXAMYEAR_FIELD_NUMBER;
    hash = (53 * hash) + getExamYear().hashCode();
    hash = (37 * hash) + PICI_FIELD_NUMBER;
    hash = (53 * hash) + getPici();
    hash = (37 * hash) + ISDELETE_FIELD_NUMBER;
    hash = (53 * hash) + getIsDelete();
    hash = (37 * hash) + CREATORID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCreatorId());
    if (getFavoredMajorCls1ListCount() > 0) {
      hash = (37 * hash) + FAVOREDMAJORCLS1LIST_FIELD_NUMBER;
      hash = (53 * hash) + getFavoredMajorCls1ListList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.msg.TemplateInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.msg.TemplateInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.msg.TemplateInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.msg.TemplateInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.msg.TemplateInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.msg.TemplateInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.msg.TemplateInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.msg.TemplateInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.msg.TemplateInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.msg.TemplateInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.msg.TemplateInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.msg.TemplateInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.msg.TemplateInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 志愿模板
   * </pre>
   *
   * Protobuf type {@code TemplateInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:TemplateInfo)
      com.msg.TemplateInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.msg.YZPM.internal_static_TemplateInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.msg.YZPM.internal_static_TemplateInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.msg.TemplateInfo.class, com.msg.TemplateInfo.Builder.class);
    }

    // Construct using com.msg.TemplateInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getFavoredMajorCls1ListFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0L;

      lastUpdateDate_ = 0L;

      templateName_ = "";

      creatorName_ = "";

      authorTeacherIds_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000001);
      isPublic_ = 0;

      examYear_ = "";

      pici_ = 0;

      isDelete_ = 0;

      creatorId_ = 0L;

      if (favoredMajorCls1ListBuilder_ == null) {
        favoredMajorCls1List_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        favoredMajorCls1ListBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.msg.YZPM.internal_static_TemplateInfo_descriptor;
    }

    @java.lang.Override
    public com.msg.TemplateInfo getDefaultInstanceForType() {
      return com.msg.TemplateInfo.getDefaultInstance();
    }

    @java.lang.Override
    public com.msg.TemplateInfo build() {
      com.msg.TemplateInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.msg.TemplateInfo buildPartial() {
      com.msg.TemplateInfo result = new com.msg.TemplateInfo(this);
      int from_bitField0_ = bitField0_;
      result.id_ = id_;
      result.lastUpdateDate_ = lastUpdateDate_;
      result.templateName_ = templateName_;
      result.creatorName_ = creatorName_;
      if (((bitField0_ & 0x00000001) != 0)) {
        authorTeacherIds_.makeImmutable();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.authorTeacherIds_ = authorTeacherIds_;
      result.isPublic_ = isPublic_;
      result.examYear_ = examYear_;
      result.pici_ = pici_;
      result.isDelete_ = isDelete_;
      result.creatorId_ = creatorId_;
      if (favoredMajorCls1ListBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          favoredMajorCls1List_ = java.util.Collections.unmodifiableList(favoredMajorCls1List_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.favoredMajorCls1List_ = favoredMajorCls1List_;
      } else {
        result.favoredMajorCls1List_ = favoredMajorCls1ListBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.msg.TemplateInfo) {
        return mergeFrom((com.msg.TemplateInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.msg.TemplateInfo other) {
      if (other == com.msg.TemplateInfo.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (other.getLastUpdateDate() != 0L) {
        setLastUpdateDate(other.getLastUpdateDate());
      }
      if (!other.getTemplateName().isEmpty()) {
        templateName_ = other.templateName_;
        onChanged();
      }
      if (!other.getCreatorName().isEmpty()) {
        creatorName_ = other.creatorName_;
        onChanged();
      }
      if (!other.authorTeacherIds_.isEmpty()) {
        if (authorTeacherIds_.isEmpty()) {
          authorTeacherIds_ = other.authorTeacherIds_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureAuthorTeacherIdsIsMutable();
          authorTeacherIds_.addAll(other.authorTeacherIds_);
        }
        onChanged();
      }
      if (other.getIsPublic() != 0) {
        setIsPublic(other.getIsPublic());
      }
      if (!other.getExamYear().isEmpty()) {
        examYear_ = other.examYear_;
        onChanged();
      }
      if (other.getPici() != 0) {
        setPici(other.getPici());
      }
      if (other.getIsDelete() != 0) {
        setIsDelete(other.getIsDelete());
      }
      if (other.getCreatorId() != 0L) {
        setCreatorId(other.getCreatorId());
      }
      if (favoredMajorCls1ListBuilder_ == null) {
        if (!other.favoredMajorCls1List_.isEmpty()) {
          if (favoredMajorCls1List_.isEmpty()) {
            favoredMajorCls1List_ = other.favoredMajorCls1List_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureFavoredMajorCls1ListIsMutable();
            favoredMajorCls1List_.addAll(other.favoredMajorCls1List_);
          }
          onChanged();
        }
      } else {
        if (!other.favoredMajorCls1List_.isEmpty()) {
          if (favoredMajorCls1ListBuilder_.isEmpty()) {
            favoredMajorCls1ListBuilder_.dispose();
            favoredMajorCls1ListBuilder_ = null;
            favoredMajorCls1List_ = other.favoredMajorCls1List_;
            bitField0_ = (bitField0_ & ~0x00000002);
            favoredMajorCls1ListBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getFavoredMajorCls1ListFieldBuilder() : null;
          } else {
            favoredMajorCls1ListBuilder_.addAllMessages(other.favoredMajorCls1List_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.msg.TemplateInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.msg.TemplateInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long id_ ;
    /**
     * <pre>
     *志愿表唯一id
     * </pre>
     *
     * <code>fixed64 id = 1;</code>
     * @return The id.
     */
    public long getId() {
      return id_;
    }
    /**
     * <pre>
     *志愿表唯一id
     * </pre>
     *
     * <code>fixed64 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *志愿表唯一id
     * </pre>
     *
     * <code>fixed64 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = 0L;
      onChanged();
      return this;
    }

    private long lastUpdateDate_ ;
    /**
     * <pre>
     *最后编辑时间
     * </pre>
     *
     * <code>int64 lastUpdateDate = 2;</code>
     * @return The lastUpdateDate.
     */
    public long getLastUpdateDate() {
      return lastUpdateDate_;
    }
    /**
     * <pre>
     *最后编辑时间
     * </pre>
     *
     * <code>int64 lastUpdateDate = 2;</code>
     * @param value The lastUpdateDate to set.
     * @return This builder for chaining.
     */
    public Builder setLastUpdateDate(long value) {
      
      lastUpdateDate_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *最后编辑时间
     * </pre>
     *
     * <code>int64 lastUpdateDate = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearLastUpdateDate() {
      
      lastUpdateDate_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object templateName_ = "";
    /**
     * <pre>
     *模板名 不能重名
     * </pre>
     *
     * <code>string templateName = 3;</code>
     * @return The templateName.
     */
    public java.lang.String getTemplateName() {
      java.lang.Object ref = templateName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        templateName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *模板名 不能重名
     * </pre>
     *
     * <code>string templateName = 3;</code>
     * @return The bytes for templateName.
     */
    public com.google.protobuf.ByteString
        getTemplateNameBytes() {
      java.lang.Object ref = templateName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        templateName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *模板名 不能重名
     * </pre>
     *
     * <code>string templateName = 3;</code>
     * @param value The templateName to set.
     * @return This builder for chaining.
     */
    public Builder setTemplateName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      templateName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *模板名 不能重名
     * </pre>
     *
     * <code>string templateName = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTemplateName() {
      
      templateName_ = getDefaultInstance().getTemplateName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *模板名 不能重名
     * </pre>
     *
     * <code>string templateName = 3;</code>
     * @param value The bytes for templateName to set.
     * @return This builder for chaining.
     */
    public Builder setTemplateNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      templateName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object creatorName_ = "";
    /**
     * <pre>
     *创建人
     * </pre>
     *
     * <code>string creatorName = 4;</code>
     * @return The creatorName.
     */
    public java.lang.String getCreatorName() {
      java.lang.Object ref = creatorName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        creatorName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *创建人
     * </pre>
     *
     * <code>string creatorName = 4;</code>
     * @return The bytes for creatorName.
     */
    public com.google.protobuf.ByteString
        getCreatorNameBytes() {
      java.lang.Object ref = creatorName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        creatorName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *创建人
     * </pre>
     *
     * <code>string creatorName = 4;</code>
     * @param value The creatorName to set.
     * @return This builder for chaining.
     */
    public Builder setCreatorName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      creatorName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *创建人
     * </pre>
     *
     * <code>string creatorName = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearCreatorName() {
      
      creatorName_ = getDefaultInstance().getCreatorName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *创建人
     * </pre>
     *
     * <code>string creatorName = 4;</code>
     * @param value The bytes for creatorName to set.
     * @return This builder for chaining.
     */
    public Builder setCreatorNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      creatorName_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.LongList authorTeacherIds_ = emptyLongList();
    private void ensureAuthorTeacherIdsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        authorTeacherIds_ = mutableCopy(authorTeacherIds_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <pre>
     *授权可查看的老师Ids [(id),(id),(id)]
     * </pre>
     *
     * <code>repeated fixed64 authorTeacherIds = 5;</code>
     * @return A list containing the authorTeacherIds.
     */
    public java.util.List<java.lang.Long>
        getAuthorTeacherIdsList() {
      return ((bitField0_ & 0x00000001) != 0) ?
               java.util.Collections.unmodifiableList(authorTeacherIds_) : authorTeacherIds_;
    }
    /**
     * <pre>
     *授权可查看的老师Ids [(id),(id),(id)]
     * </pre>
     *
     * <code>repeated fixed64 authorTeacherIds = 5;</code>
     * @return The count of authorTeacherIds.
     */
    public int getAuthorTeacherIdsCount() {
      return authorTeacherIds_.size();
    }
    /**
     * <pre>
     *授权可查看的老师Ids [(id),(id),(id)]
     * </pre>
     *
     * <code>repeated fixed64 authorTeacherIds = 5;</code>
     * @param index The index of the element to return.
     * @return The authorTeacherIds at the given index.
     */
    public long getAuthorTeacherIds(int index) {
      return authorTeacherIds_.getLong(index);
    }
    /**
     * <pre>
     *授权可查看的老师Ids [(id),(id),(id)]
     * </pre>
     *
     * <code>repeated fixed64 authorTeacherIds = 5;</code>
     * @param index The index to set the value at.
     * @param value The authorTeacherIds to set.
     * @return This builder for chaining.
     */
    public Builder setAuthorTeacherIds(
        int index, long value) {
      ensureAuthorTeacherIdsIsMutable();
      authorTeacherIds_.setLong(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *授权可查看的老师Ids [(id),(id),(id)]
     * </pre>
     *
     * <code>repeated fixed64 authorTeacherIds = 5;</code>
     * @param value The authorTeacherIds to add.
     * @return This builder for chaining.
     */
    public Builder addAuthorTeacherIds(long value) {
      ensureAuthorTeacherIdsIsMutable();
      authorTeacherIds_.addLong(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *授权可查看的老师Ids [(id),(id),(id)]
     * </pre>
     *
     * <code>repeated fixed64 authorTeacherIds = 5;</code>
     * @param values The authorTeacherIds to add.
     * @return This builder for chaining.
     */
    public Builder addAllAuthorTeacherIds(
        java.lang.Iterable<? extends java.lang.Long> values) {
      ensureAuthorTeacherIdsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, authorTeacherIds_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *授权可查看的老师Ids [(id),(id),(id)]
     * </pre>
     *
     * <code>repeated fixed64 authorTeacherIds = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearAuthorTeacherIds() {
      authorTeacherIds_ = emptyLongList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }

    private int isPublic_ ;
    /**
     * <pre>
     *1: 公开; 0: 没有公开
     * </pre>
     *
     * <code>int32 isPublic = 6;</code>
     * @return The isPublic.
     */
    public int getIsPublic() {
      return isPublic_;
    }
    /**
     * <pre>
     *1: 公开; 0: 没有公开
     * </pre>
     *
     * <code>int32 isPublic = 6;</code>
     * @param value The isPublic to set.
     * @return This builder for chaining.
     */
    public Builder setIsPublic(int value) {
      
      isPublic_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *1: 公开; 0: 没有公开
     * </pre>
     *
     * <code>int32 isPublic = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsPublic() {
      
      isPublic_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object examYear_ = "";
    /**
     * <pre>
     *志愿年份
     * </pre>
     *
     * <code>string examYear = 7;</code>
     * @return The examYear.
     */
    public java.lang.String getExamYear() {
      java.lang.Object ref = examYear_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        examYear_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *志愿年份
     * </pre>
     *
     * <code>string examYear = 7;</code>
     * @return The bytes for examYear.
     */
    public com.google.protobuf.ByteString
        getExamYearBytes() {
      java.lang.Object ref = examYear_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        examYear_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *志愿年份
     * </pre>
     *
     * <code>string examYear = 7;</code>
     * @param value The examYear to set.
     * @return This builder for chaining.
     */
    public Builder setExamYear(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      examYear_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *志愿年份
     * </pre>
     *
     * <code>string examYear = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearExamYear() {
      
      examYear_ = getDefaultInstance().getExamYear();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *志愿年份
     * </pre>
     *
     * <code>string examYear = 7;</code>
     * @param value The bytes for examYear to set.
     * @return This builder for chaining.
     */
    public Builder setExamYearBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      examYear_ = value;
      onChanged();
      return this;
    }

    private int pici_ ;
    /**
     * <pre>
     *批次: 1: 本科A,2:本科B, 3: 提前批本A, 4:提前批本B
     * </pre>
     *
     * <code>int32 pici = 8;</code>
     * @return The pici.
     */
    public int getPici() {
      return pici_;
    }
    /**
     * <pre>
     *批次: 1: 本科A,2:本科B, 3: 提前批本A, 4:提前批本B
     * </pre>
     *
     * <code>int32 pici = 8;</code>
     * @param value The pici to set.
     * @return This builder for chaining.
     */
    public Builder setPici(int value) {
      
      pici_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *批次: 1: 本科A,2:本科B, 3: 提前批本A, 4:提前批本B
     * </pre>
     *
     * <code>int32 pici = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearPici() {
      
      pici_ = 0;
      onChanged();
      return this;
    }

    private int isDelete_ ;
    /**
     * <pre>
     *1: 已经删除; 0: 没有删除
     * </pre>
     *
     * <code>int32 isDelete = 9;</code>
     * @return The isDelete.
     */
    public int getIsDelete() {
      return isDelete_;
    }
    /**
     * <pre>
     *1: 已经删除; 0: 没有删除
     * </pre>
     *
     * <code>int32 isDelete = 9;</code>
     * @param value The isDelete to set.
     * @return This builder for chaining.
     */
    public Builder setIsDelete(int value) {
      
      isDelete_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *1: 已经删除; 0: 没有删除
     * </pre>
     *
     * <code>int32 isDelete = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsDelete() {
      
      isDelete_ = 0;
      onChanged();
      return this;
    }

    private long creatorId_ ;
    /**
     * <pre>
     *创建人 id
     * </pre>
     *
     * <code>int64 creatorId = 10;</code>
     * @return The creatorId.
     */
    public long getCreatorId() {
      return creatorId_;
    }
    /**
     * <pre>
     *创建人 id
     * </pre>
     *
     * <code>int64 creatorId = 10;</code>
     * @param value The creatorId to set.
     * @return This builder for chaining.
     */
    public Builder setCreatorId(long value) {
      
      creatorId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *创建人 id
     * </pre>
     *
     * <code>int64 creatorId = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearCreatorId() {
      
      creatorId_ = 0L;
      onChanged();
      return this;
    }

    private java.util.List<com.msg.Major1stClsInfo> favoredMajorCls1List_ =
      java.util.Collections.emptyList();
    private void ensureFavoredMajorCls1ListIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        favoredMajorCls1List_ = new java.util.ArrayList<com.msg.Major1stClsInfo>(favoredMajorCls1List_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.msg.Major1stClsInfo, com.msg.Major1stClsInfo.Builder, com.msg.Major1stClsInfoOrBuilder> favoredMajorCls1ListBuilder_;

    /**
     * <pre>
     *模板相关的 专业信息list,
     * </pre>
     *
     * <code>repeated .Major1stClsInfo favoredMajorCls1List = 11;</code>
     */
    public java.util.List<com.msg.Major1stClsInfo> getFavoredMajorCls1ListList() {
      if (favoredMajorCls1ListBuilder_ == null) {
        return java.util.Collections.unmodifiableList(favoredMajorCls1List_);
      } else {
        return favoredMajorCls1ListBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     *模板相关的 专业信息list,
     * </pre>
     *
     * <code>repeated .Major1stClsInfo favoredMajorCls1List = 11;</code>
     */
    public int getFavoredMajorCls1ListCount() {
      if (favoredMajorCls1ListBuilder_ == null) {
        return favoredMajorCls1List_.size();
      } else {
        return favoredMajorCls1ListBuilder_.getCount();
      }
    }
    /**
     * <pre>
     *模板相关的 专业信息list,
     * </pre>
     *
     * <code>repeated .Major1stClsInfo favoredMajorCls1List = 11;</code>
     */
    public com.msg.Major1stClsInfo getFavoredMajorCls1List(int index) {
      if (favoredMajorCls1ListBuilder_ == null) {
        return favoredMajorCls1List_.get(index);
      } else {
        return favoredMajorCls1ListBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     *模板相关的 专业信息list,
     * </pre>
     *
     * <code>repeated .Major1stClsInfo favoredMajorCls1List = 11;</code>
     */
    public Builder setFavoredMajorCls1List(
        int index, com.msg.Major1stClsInfo value) {
      if (favoredMajorCls1ListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFavoredMajorCls1ListIsMutable();
        favoredMajorCls1List_.set(index, value);
        onChanged();
      } else {
        favoredMajorCls1ListBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     *模板相关的 专业信息list,
     * </pre>
     *
     * <code>repeated .Major1stClsInfo favoredMajorCls1List = 11;</code>
     */
    public Builder setFavoredMajorCls1List(
        int index, com.msg.Major1stClsInfo.Builder builderForValue) {
      if (favoredMajorCls1ListBuilder_ == null) {
        ensureFavoredMajorCls1ListIsMutable();
        favoredMajorCls1List_.set(index, builderForValue.build());
        onChanged();
      } else {
        favoredMajorCls1ListBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *模板相关的 专业信息list,
     * </pre>
     *
     * <code>repeated .Major1stClsInfo favoredMajorCls1List = 11;</code>
     */
    public Builder addFavoredMajorCls1List(com.msg.Major1stClsInfo value) {
      if (favoredMajorCls1ListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFavoredMajorCls1ListIsMutable();
        favoredMajorCls1List_.add(value);
        onChanged();
      } else {
        favoredMajorCls1ListBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     *模板相关的 专业信息list,
     * </pre>
     *
     * <code>repeated .Major1stClsInfo favoredMajorCls1List = 11;</code>
     */
    public Builder addFavoredMajorCls1List(
        int index, com.msg.Major1stClsInfo value) {
      if (favoredMajorCls1ListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFavoredMajorCls1ListIsMutable();
        favoredMajorCls1List_.add(index, value);
        onChanged();
      } else {
        favoredMajorCls1ListBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     *模板相关的 专业信息list,
     * </pre>
     *
     * <code>repeated .Major1stClsInfo favoredMajorCls1List = 11;</code>
     */
    public Builder addFavoredMajorCls1List(
        com.msg.Major1stClsInfo.Builder builderForValue) {
      if (favoredMajorCls1ListBuilder_ == null) {
        ensureFavoredMajorCls1ListIsMutable();
        favoredMajorCls1List_.add(builderForValue.build());
        onChanged();
      } else {
        favoredMajorCls1ListBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *模板相关的 专业信息list,
     * </pre>
     *
     * <code>repeated .Major1stClsInfo favoredMajorCls1List = 11;</code>
     */
    public Builder addFavoredMajorCls1List(
        int index, com.msg.Major1stClsInfo.Builder builderForValue) {
      if (favoredMajorCls1ListBuilder_ == null) {
        ensureFavoredMajorCls1ListIsMutable();
        favoredMajorCls1List_.add(index, builderForValue.build());
        onChanged();
      } else {
        favoredMajorCls1ListBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *模板相关的 专业信息list,
     * </pre>
     *
     * <code>repeated .Major1stClsInfo favoredMajorCls1List = 11;</code>
     */
    public Builder addAllFavoredMajorCls1List(
        java.lang.Iterable<? extends com.msg.Major1stClsInfo> values) {
      if (favoredMajorCls1ListBuilder_ == null) {
        ensureFavoredMajorCls1ListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, favoredMajorCls1List_);
        onChanged();
      } else {
        favoredMajorCls1ListBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     *模板相关的 专业信息list,
     * </pre>
     *
     * <code>repeated .Major1stClsInfo favoredMajorCls1List = 11;</code>
     */
    public Builder clearFavoredMajorCls1List() {
      if (favoredMajorCls1ListBuilder_ == null) {
        favoredMajorCls1List_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        favoredMajorCls1ListBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     *模板相关的 专业信息list,
     * </pre>
     *
     * <code>repeated .Major1stClsInfo favoredMajorCls1List = 11;</code>
     */
    public Builder removeFavoredMajorCls1List(int index) {
      if (favoredMajorCls1ListBuilder_ == null) {
        ensureFavoredMajorCls1ListIsMutable();
        favoredMajorCls1List_.remove(index);
        onChanged();
      } else {
        favoredMajorCls1ListBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     *模板相关的 专业信息list,
     * </pre>
     *
     * <code>repeated .Major1stClsInfo favoredMajorCls1List = 11;</code>
     */
    public com.msg.Major1stClsInfo.Builder getFavoredMajorCls1ListBuilder(
        int index) {
      return getFavoredMajorCls1ListFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     *模板相关的 专业信息list,
     * </pre>
     *
     * <code>repeated .Major1stClsInfo favoredMajorCls1List = 11;</code>
     */
    public com.msg.Major1stClsInfoOrBuilder getFavoredMajorCls1ListOrBuilder(
        int index) {
      if (favoredMajorCls1ListBuilder_ == null) {
        return favoredMajorCls1List_.get(index);  } else {
        return favoredMajorCls1ListBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     *模板相关的 专业信息list,
     * </pre>
     *
     * <code>repeated .Major1stClsInfo favoredMajorCls1List = 11;</code>
     */
    public java.util.List<? extends com.msg.Major1stClsInfoOrBuilder> 
         getFavoredMajorCls1ListOrBuilderList() {
      if (favoredMajorCls1ListBuilder_ != null) {
        return favoredMajorCls1ListBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(favoredMajorCls1List_);
      }
    }
    /**
     * <pre>
     *模板相关的 专业信息list,
     * </pre>
     *
     * <code>repeated .Major1stClsInfo favoredMajorCls1List = 11;</code>
     */
    public com.msg.Major1stClsInfo.Builder addFavoredMajorCls1ListBuilder() {
      return getFavoredMajorCls1ListFieldBuilder().addBuilder(
          com.msg.Major1stClsInfo.getDefaultInstance());
    }
    /**
     * <pre>
     *模板相关的 专业信息list,
     * </pre>
     *
     * <code>repeated .Major1stClsInfo favoredMajorCls1List = 11;</code>
     */
    public com.msg.Major1stClsInfo.Builder addFavoredMajorCls1ListBuilder(
        int index) {
      return getFavoredMajorCls1ListFieldBuilder().addBuilder(
          index, com.msg.Major1stClsInfo.getDefaultInstance());
    }
    /**
     * <pre>
     *模板相关的 专业信息list,
     * </pre>
     *
     * <code>repeated .Major1stClsInfo favoredMajorCls1List = 11;</code>
     */
    public java.util.List<com.msg.Major1stClsInfo.Builder> 
         getFavoredMajorCls1ListBuilderList() {
      return getFavoredMajorCls1ListFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.msg.Major1stClsInfo, com.msg.Major1stClsInfo.Builder, com.msg.Major1stClsInfoOrBuilder> 
        getFavoredMajorCls1ListFieldBuilder() {
      if (favoredMajorCls1ListBuilder_ == null) {
        favoredMajorCls1ListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.msg.Major1stClsInfo, com.msg.Major1stClsInfo.Builder, com.msg.Major1stClsInfoOrBuilder>(
                favoredMajorCls1List_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        favoredMajorCls1List_ = null;
      }
      return favoredMajorCls1ListBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:TemplateInfo)
  }

  // @@protoc_insertion_point(class_scope:TemplateInfo)
  private static final com.msg.TemplateInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.msg.TemplateInfo();
  }

  public static com.msg.TemplateInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TemplateInfo>
      PARSER = new com.google.protobuf.AbstractParser<TemplateInfo>() {
    @java.lang.Override
    public TemplateInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TemplateInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TemplateInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TemplateInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.msg.TemplateInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

