// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: yzpm.proto

package com.msg;

public interface UniMajorInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UniMajorInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *id
   * </pre>
   *
   * <code>fixed64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <pre>
   *院校专业组代码
   * </pre>
   *
   * <code>string uniMajorCode = 2;</code>
   * @return The uniMajorCode.
   */
  java.lang.String getUniMajorCode();
  /**
   * <pre>
   *院校专业组代码
   * </pre>
   *
   * <code>string uniMajorCode = 2;</code>
   * @return The bytes for uniMajorCode.
   */
  com.google.protobuf.ByteString
      getUniMajorCodeBytes();

  /**
   * <pre>
   *批次: 1: 本科A,2:本科B, 3: 提前批本A, 4:提前批本B   5: 专科批次
   * </pre>
   *
   * <code>int32 pici = 3;</code>
   * @return The pici.
   */
  int getPici();

  /**
   * <pre>
   *院校名称
   * </pre>
   *
   * <code>string schoolName = 4;</code>
   * @return The schoolName.
   */
  java.lang.String getSchoolName();
  /**
   * <pre>
   *院校名称
   * </pre>
   *
   * <code>string schoolName = 4;</code>
   * @return The bytes for schoolName.
   */
  com.google.protobuf.ByteString
      getSchoolNameBytes();

  /**
   * <pre>
   *双一流,
   * </pre>
   *
   * <code>int32 schoolLvl1 = 5;</code>
   * @return The schoolLvl1.
   */
  int getSchoolLvl1();

  /**
   * <pre>
   *985; 用1表示 正确
   * </pre>
   *
   * <code>int32 schoolLvl2 = 6;</code>
   * @return The schoolLvl2.
   */
  int getSchoolLvl2();

  /**
   * <pre>
   *211 用1表示
   * </pre>
   *
   * <code>int32 schoolLvl3 = 7;</code>
   * @return The schoolLvl3.
   */
  int getSchoolLvl3();

  /**
   * <pre>
   *院校类型 综合, 理工、综合、师范、医药
   * </pre>
   *
   * <code>string schoolType = 8;</code>
   * @return The schoolType.
   */
  java.lang.String getSchoolType();
  /**
   * <pre>
   *院校类型 综合, 理工、综合、师范、医药
   * </pre>
   *
   * <code>string schoolType = 8;</code>
   * @return The bytes for schoolType.
   */
  com.google.protobuf.ByteString
      getSchoolTypeBytes();

  /**
   * <pre>
   *省
   * </pre>
   *
   * <code>string province = 9;</code>
   * @return The province.
   */
  java.lang.String getProvince();
  /**
   * <pre>
   *省
   * </pre>
   *
   * <code>string province = 9;</code>
   * @return The bytes for province.
   */
  com.google.protobuf.ByteString
      getProvinceBytes();

  /**
   * <pre>
   *市
   * </pre>
   *
   * <code>string city = 10;</code>
   * @return The city.
   */
  java.lang.String getCity();
  /**
   * <pre>
   *市
   * </pre>
   *
   * <code>string city = 10;</code>
   * @return The bytes for city.
   */
  com.google.protobuf.ByteString
      getCityBytes();

  /**
   * <pre>
   *隶属
   * </pre>
   *
   * <code>string belongDep = 11;</code>
   * @return The belongDep.
   */
  java.lang.String getBelongDep();
  /**
   * <pre>
   *隶属
   * </pre>
   *
   * <code>string belongDep = 11;</code>
   * @return The bytes for belongDep.
   */
  com.google.protobuf.ByteString
      getBelongDepBytes();

  /**
   * <pre>
   *录取规则
   * </pre>
   *
   * <code>string admissionRule = 12;</code>
   * @return The admissionRule.
   */
  java.lang.String getAdmissionRule();
  /**
   * <pre>
   *录取规则
   * </pre>
   *
   * <code>string admissionRule = 12;</code>
   * @return The bytes for admissionRule.
   */
  com.google.protobuf.ByteString
      getAdmissionRuleBytes();

  /**
   * <pre>
   *排名
   * </pre>
   *
   * <code>string schoolRank = 13;</code>
   * @return The schoolRank.
   */
  java.lang.String getSchoolRank();
  /**
   * <pre>
   *排名
   * </pre>
   *
   * <code>string schoolRank = 13;</code>
   * @return The bytes for schoolRank.
   */
  com.google.protobuf.ByteString
      getSchoolRankBytes();

  /**
   * <pre>
   *22计划数 = 组内求和
   * </pre>
   *
   * <code>string studentNum22Plan = 14;</code>
   * @return The studentNum22Plan.
   */
  java.lang.String getStudentNum22Plan();
  /**
   * <pre>
   *22计划数 = 组内求和
   * </pre>
   *
   * <code>string studentNum22Plan = 14;</code>
   * @return The bytes for studentNum22Plan.
   */
  com.google.protobuf.ByteString
      getStudentNum22PlanBytes();

  /**
   * <pre>
   *科目要求
   * </pre>
   *
   * <code>string subjectRequirement = 15;</code>
   * @return The subjectRequirement.
   */
  java.lang.String getSubjectRequirement();
  /**
   * <pre>
   *科目要求
   * </pre>
   *
   * <code>string subjectRequirement = 15;</code>
   * @return The bytes for subjectRequirement.
   */
  com.google.protobuf.ByteString
      getSubjectRequirementBytes();

  /**
   * <pre>
   *22录取数 = 组内求和
   * </pre>
   *
   * <code>string studentNum22Admit = 16;</code>
   * @return The studentNum22Admit.
   */
  java.lang.String getStudentNum22Admit();
  /**
   * <pre>
   *22录取数 = 组内求和
   * </pre>
   *
   * <code>string studentNum22Admit = 16;</code>
   * @return The bytes for studentNum22Admit.
   */
  com.google.protobuf.ByteString
      getStudentNum22AdmitBytes();

  /**
   * <pre>
   *22组分数
   * </pre>
   *
   * <code>string scoreFor22 = 17;</code>
   * @return The scoreFor22.
   */
  java.lang.String getScoreFor22();
  /**
   * <pre>
   *22组分数
   * </pre>
   *
   * <code>string scoreFor22 = 17;</code>
   * @return The bytes for scoreFor22.
   */
  com.google.protobuf.ByteString
      getScoreFor22Bytes();

  /**
   * <pre>
   *22组位次
   * </pre>
   *
   * <code>string rankFor22 = 18;</code>
   * @return The rankFor22.
   */
  java.lang.String getRankFor22();
  /**
   * <pre>
   *22组位次
   * </pre>
   *
   * <code>string rankFor22 = 18;</code>
   * @return The bytes for rankFor22.
   */
  com.google.protobuf.ByteString
      getRankFor22Bytes();

  /**
   * <pre>
   *21年计划数 = 组内求和
   * </pre>
   *
   * <code>string studentNum21Plan = 19;</code>
   * @return The studentNum21Plan.
   */
  java.lang.String getStudentNum21Plan();
  /**
   * <pre>
   *21年计划数 = 组内求和
   * </pre>
   *
   * <code>string studentNum21Plan = 19;</code>
   * @return The bytes for studentNum21Plan.
   */
  com.google.protobuf.ByteString
      getStudentNum21PlanBytes();

  /**
   * <pre>
   *21录取数 = 组内求和
   * </pre>
   *
   * <code>string studentNum21Admit = 20;</code>
   * @return The studentNum21Admit.
   */
  java.lang.String getStudentNum21Admit();
  /**
   * <pre>
   *21录取数 = 组内求和
   * </pre>
   *
   * <code>string studentNum21Admit = 20;</code>
   * @return The bytes for studentNum21Admit.
   */
  com.google.protobuf.ByteString
      getStudentNum21AdmitBytes();

  /**
   * <pre>
   *21组分数
   * </pre>
   *
   * <code>string scoreFor21 = 21;</code>
   * @return The scoreFor21.
   */
  java.lang.String getScoreFor21();
  /**
   * <pre>
   *21组分数
   * </pre>
   *
   * <code>string scoreFor21 = 21;</code>
   * @return The bytes for scoreFor21.
   */
  com.google.protobuf.ByteString
      getScoreFor21Bytes();

  /**
   * <pre>
   *21组位次
   * </pre>
   *
   * <code>string rankFor21 = 22;</code>
   * @return The rankFor21.
   */
  java.lang.String getRankFor21();
  /**
   * <pre>
   *21组位次
   * </pre>
   *
   * <code>string rankFor21 = 22;</code>
   * @return The bytes for rankFor21.
   */
  com.google.protobuf.ByteString
      getRankFor21Bytes();

  /**
   * <pre>
   *20年计划数 = 组内求和
   * </pre>
   *
   * <code>string studentNum20Plan = 23;</code>
   * @return The studentNum20Plan.
   */
  java.lang.String getStudentNum20Plan();
  /**
   * <pre>
   *20年计划数 = 组内求和
   * </pre>
   *
   * <code>string studentNum20Plan = 23;</code>
   * @return The bytes for studentNum20Plan.
   */
  com.google.protobuf.ByteString
      getStudentNum20PlanBytes();

  /**
   * <pre>
   *20录取数 = 组内求和
   * </pre>
   *
   * <code>string studentNum20Admit = 24;</code>
   * @return The studentNum20Admit.
   */
  java.lang.String getStudentNum20Admit();
  /**
   * <pre>
   *20录取数 = 组内求和
   * </pre>
   *
   * <code>string studentNum20Admit = 24;</code>
   * @return The bytes for studentNum20Admit.
   */
  com.google.protobuf.ByteString
      getStudentNum20AdmitBytes();

  /**
   * <pre>
   *20组分数
   * </pre>
   *
   * <code>string scoreFor20 = 25;</code>
   * @return The scoreFor20.
   */
  java.lang.String getScoreFor20();
  /**
   * <pre>
   *20组分数
   * </pre>
   *
   * <code>string scoreFor20 = 25;</code>
   * @return The bytes for scoreFor20.
   */
  com.google.protobuf.ByteString
      getScoreFor20Bytes();

  /**
   * <pre>
   *20组位次
   * </pre>
   *
   * <code>string rankFor20 = 26;</code>
   * @return The rankFor20.
   */
  java.lang.String getRankFor20();
  /**
   * <pre>
   *20组位次
   * </pre>
   *
   * <code>string rankFor20 = 26;</code>
   * @return The bytes for rankFor20.
   */
  com.google.protobuf.ByteString
      getRankFor20Bytes();

  /**
   * <pre>
   *专业代码
   * </pre>
   *
   * <code>string majorCode = 27;</code>
   * @return The majorCode.
   */
  java.lang.String getMajorCode();
  /**
   * <pre>
   *专业代码
   * </pre>
   *
   * <code>string majorCode = 27;</code>
   * @return The bytes for majorCode.
   */
  com.google.protobuf.ByteString
      getMajorCodeBytes();

  /**
   * <pre>
   *专业名称
   * </pre>
   *
   * <code>string majorName = 28;</code>
   * @return The majorName.
   */
  java.lang.String getMajorName();
  /**
   * <pre>
   *专业名称
   * </pre>
   *
   * <code>string majorName = 28;</code>
   * @return The bytes for majorName.
   */
  com.google.protobuf.ByteString
      getMajorNameBytes();

  /**
   * <pre>
   *专业备注
   * </pre>
   *
   * <code>string majorComments = 29;</code>
   * @return The majorComments.
   */
  java.lang.String getMajorComments();
  /**
   * <pre>
   *专业备注
   * </pre>
   *
   * <code>string majorComments = 29;</code>
   * @return The bytes for majorComments.
   */
  com.google.protobuf.ByteString
      getMajorCommentsBytes();

  /**
   * <pre>
   *专业其他信息
   * </pre>
   *
   * <code>string majorOtherInfo = 30;</code>
   * @return The majorOtherInfo.
   */
  java.lang.String getMajorOtherInfo();
  /**
   * <pre>
   *专业其他信息
   * </pre>
   *
   * <code>string majorOtherInfo = 30;</code>
   * @return The bytes for majorOtherInfo.
   */
  com.google.protobuf.ByteString
      getMajorOtherInfoBytes();

  /**
   * <pre>
   *外语语种
   * </pre>
   *
   * <code>string requireLang = 31;</code>
   * @return The requireLang.
   */
  java.lang.String getRequireLang();
  /**
   * <pre>
   *外语语种
   * </pre>
   *
   * <code>string requireLang = 31;</code>
   * @return The bytes for requireLang.
   */
  com.google.protobuf.ByteString
      getRequireLangBytes();

  /**
   * <pre>
   *是否口试
   * </pre>
   *
   * <code>string requireInterview = 32;</code>
   * @return The requireInterview.
   */
  java.lang.String getRequireInterview();
  /**
   * <pre>
   *是否口试
   * </pre>
   *
   * <code>string requireInterview = 32;</code>
   * @return The bytes for requireInterview.
   */
  com.google.protobuf.ByteString
      getRequireInterviewBytes();

  /**
   * <pre>
   *学制
   * </pre>
   *
   * <code>string majorDuration = 33;</code>
   * @return The majorDuration.
   */
  java.lang.String getMajorDuration();
  /**
   * <pre>
   *学制
   * </pre>
   *
   * <code>string majorDuration = 33;</code>
   * @return The bytes for majorDuration.
   */
  com.google.protobuf.ByteString
      getMajorDurationBytes();

  /**
   * <pre>
   *收费标准
   * </pre>
   *
   * <code>string majorTuition = 34;</code>
   * @return The majorTuition.
   */
  java.lang.String getMajorTuition();
  /**
   * <pre>
   *收费标准
   * </pre>
   *
   * <code>string majorTuition = 34;</code>
   * @return The bytes for majorTuition.
   */
  com.google.protobuf.ByteString
      getMajorTuitionBytes();

  /**
   * <pre>
   *22年计划数
   * </pre>
   *
   * <code>string major22Plan = 35;</code>
   * @return The major22Plan.
   */
  java.lang.String getMajor22Plan();
  /**
   * <pre>
   *22年计划数
   * </pre>
   *
   * <code>string major22Plan = 35;</code>
   * @return The bytes for major22Plan.
   */
  com.google.protobuf.ByteString
      getMajor22PlanBytes();

  /**
   * <pre>
   *22录取数
   * </pre>
   *
   * <code>string major22Admin = 36;</code>
   * @return The major22Admin.
   */
  java.lang.String getMajor22Admin();
  /**
   * <pre>
   *22录取数
   * </pre>
   *
   * <code>string major22Admin = 36;</code>
   * @return The bytes for major22Admin.
   */
  com.google.protobuf.ByteString
      getMajor22AdminBytes();

  /**
   * <pre>
   *22年低
   * </pre>
   *
   * <code>string major22LowScore = 37;</code>
   * @return The major22LowScore.
   */
  java.lang.String getMajor22LowScore();
  /**
   * <pre>
   *22年低
   * </pre>
   *
   * <code>string major22LowScore = 37;</code>
   * @return The bytes for major22LowScore.
   */
  com.google.protobuf.ByteString
      getMajor22LowScoreBytes();

  /**
   * <pre>
   *22年低位次
   * </pre>
   *
   * <code>string major22LowRank = 38;</code>
   * @return The major22LowRank.
   */
  java.lang.String getMajor22LowRank();
  /**
   * <pre>
   *22年低位次
   * </pre>
   *
   * <code>string major22LowRank = 38;</code>
   * @return The bytes for major22LowRank.
   */
  com.google.protobuf.ByteString
      getMajor22LowRankBytes();

  /**
   * <pre>
   *21年计划数
   * </pre>
   *
   * <code>string major21Plan = 39;</code>
   * @return The major21Plan.
   */
  java.lang.String getMajor21Plan();
  /**
   * <pre>
   *21年计划数
   * </pre>
   *
   * <code>string major21Plan = 39;</code>
   * @return The bytes for major21Plan.
   */
  com.google.protobuf.ByteString
      getMajor21PlanBytes();

  /**
   * <pre>
   *21录取数
   * </pre>
   *
   * <code>string major21Admin = 40;</code>
   * @return The major21Admin.
   */
  java.lang.String getMajor21Admin();
  /**
   * <pre>
   *21录取数
   * </pre>
   *
   * <code>string major21Admin = 40;</code>
   * @return The bytes for major21Admin.
   */
  com.google.protobuf.ByteString
      getMajor21AdminBytes();

  /**
   * <pre>
   *21年低
   * </pre>
   *
   * <code>string major21LowScore = 41;</code>
   * @return The major21LowScore.
   */
  java.lang.String getMajor21LowScore();
  /**
   * <pre>
   *21年低
   * </pre>
   *
   * <code>string major21LowScore = 41;</code>
   * @return The bytes for major21LowScore.
   */
  com.google.protobuf.ByteString
      getMajor21LowScoreBytes();

  /**
   * <pre>
   *21年低位次
   * </pre>
   *
   * <code>string major21LowRank = 42;</code>
   * @return The major21LowRank.
   */
  java.lang.String getMajor21LowRank();
  /**
   * <pre>
   *21年低位次
   * </pre>
   *
   * <code>string major21LowRank = 42;</code>
   * @return The bytes for major21LowRank.
   */
  com.google.protobuf.ByteString
      getMajor21LowRankBytes();

  /**
   * <pre>
   *20年计划数
   * </pre>
   *
   * <code>string major20Plan = 43;</code>
   * @return The major20Plan.
   */
  java.lang.String getMajor20Plan();
  /**
   * <pre>
   *20年计划数
   * </pre>
   *
   * <code>string major20Plan = 43;</code>
   * @return The bytes for major20Plan.
   */
  com.google.protobuf.ByteString
      getMajor20PlanBytes();

  /**
   * <pre>
   *20录取数
   * </pre>
   *
   * <code>string major20Admin = 44;</code>
   * @return The major20Admin.
   */
  java.lang.String getMajor20Admin();
  /**
   * <pre>
   *20录取数
   * </pre>
   *
   * <code>string major20Admin = 44;</code>
   * @return The bytes for major20Admin.
   */
  com.google.protobuf.ByteString
      getMajor20AdminBytes();

  /**
   * <pre>
   *20年低
   * </pre>
   *
   * <code>string major20LowScore = 45;</code>
   * @return The major20LowScore.
   */
  java.lang.String getMajor20LowScore();
  /**
   * <pre>
   *20年低
   * </pre>
   *
   * <code>string major20LowScore = 45;</code>
   * @return The bytes for major20LowScore.
   */
  com.google.protobuf.ByteString
      getMajor20LowScoreBytes();

  /**
   * <pre>
   *20年低位次
   * </pre>
   *
   * <code>string major20LowRank = 46;</code>
   * @return The major20LowRank.
   */
  java.lang.String getMajor20LowRank();
  /**
   * <pre>
   *20年低位次
   * </pre>
   *
   * <code>string major20LowRank = 46;</code>
   * @return The bytes for major20LowRank.
   */
  com.google.protobuf.ByteString
      getMajor20LowRankBytes();

  /**
   * <pre>
   *专业类表 ids [id,id,id]
   * </pre>
   *
   * <code>repeated fixed64 majorClsIds = 47;</code>
   * @return A list containing the majorClsIds.
   */
  java.util.List<java.lang.Long> getMajorClsIdsList();
  /**
   * <pre>
   *专业类表 ids [id,id,id]
   * </pre>
   *
   * <code>repeated fixed64 majorClsIds = 47;</code>
   * @return The count of majorClsIds.
   */
  int getMajorClsIdsCount();
  /**
   * <pre>
   *专业类表 ids [id,id,id]
   * </pre>
   *
   * <code>repeated fixed64 majorClsIds = 47;</code>
   * @param index The index of the element to return.
   * @return The majorClsIds at the given index.
   */
  long getMajorClsIds(int index);

  /**
   * <pre>
   *保存icon 图片
   * </pre>
   *
   * <code>repeated string majorIcon = 48;</code>
   * @return A list containing the majorIcon.
   */
  java.util.List<java.lang.String>
      getMajorIconList();
  /**
   * <pre>
   *保存icon 图片
   * </pre>
   *
   * <code>repeated string majorIcon = 48;</code>
   * @return The count of majorIcon.
   */
  int getMajorIconCount();
  /**
   * <pre>
   *保存icon 图片
   * </pre>
   *
   * <code>repeated string majorIcon = 48;</code>
   * @param index The index of the element to return.
   * @return The majorIcon at the given index.
   */
  java.lang.String getMajorIcon(int index);
  /**
   * <pre>
   *保存icon 图片
   * </pre>
   *
   * <code>repeated string majorIcon = 48;</code>
   * @param index The index of the value to return.
   * @return The bytes of the majorIcon at the given index.
   */
  com.google.protobuf.ByteString
      getMajorIconBytes(int index);

  /**
   * <pre>
   *22年高分
   * </pre>
   *
   * <code>string major22HScore = 49;</code>
   * @return The major22HScore.
   */
  java.lang.String getMajor22HScore();
  /**
   * <pre>
   *22年高分
   * </pre>
   *
   * <code>string major22HScore = 49;</code>
   * @return The bytes for major22HScore.
   */
  com.google.protobuf.ByteString
      getMajor22HScoreBytes();

  /**
   * <pre>
   *22年高位次
   * </pre>
   *
   * <code>string major22HRank = 50;</code>
   * @return The major22HRank.
   */
  java.lang.String getMajor22HRank();
  /**
   * <pre>
   *22年高位次
   * </pre>
   *
   * <code>string major22HRank = 50;</code>
   * @return The bytes for major22HRank.
   */
  com.google.protobuf.ByteString
      getMajor22HRankBytes();

  /**
   * <pre>
   *22年平均分
   * </pre>
   *
   * <code>string major22AvgScore = 51;</code>
   * @return The major22AvgScore.
   */
  java.lang.String getMajor22AvgScore();
  /**
   * <pre>
   *22年平均分
   * </pre>
   *
   * <code>string major22AvgScore = 51;</code>
   * @return The bytes for major22AvgScore.
   */
  com.google.protobuf.ByteString
      getMajor22AvgScoreBytes();

  /**
   * <pre>
   *22年平均位次
   * </pre>
   *
   * <code>string major22AvgRank = 52;</code>
   * @return The major22AvgRank.
   */
  java.lang.String getMajor22AvgRank();
  /**
   * <pre>
   *22年平均位次
   * </pre>
   *
   * <code>string major22AvgRank = 52;</code>
   * @return The bytes for major22AvgRank.
   */
  com.google.protobuf.ByteString
      getMajor22AvgRankBytes();

  /**
   * <pre>
   *21年高分
   * </pre>
   *
   * <code>string major21HScore = 53;</code>
   * @return The major21HScore.
   */
  java.lang.String getMajor21HScore();
  /**
   * <pre>
   *21年高分
   * </pre>
   *
   * <code>string major21HScore = 53;</code>
   * @return The bytes for major21HScore.
   */
  com.google.protobuf.ByteString
      getMajor21HScoreBytes();

  /**
   * <pre>
   *21年高位次
   * </pre>
   *
   * <code>string major21HRank = 54;</code>
   * @return The major21HRank.
   */
  java.lang.String getMajor21HRank();
  /**
   * <pre>
   *21年高位次
   * </pre>
   *
   * <code>string major21HRank = 54;</code>
   * @return The bytes for major21HRank.
   */
  com.google.protobuf.ByteString
      getMajor21HRankBytes();

  /**
   * <pre>
   *21年平均分
   * </pre>
   *
   * <code>string major21AvgScore = 55;</code>
   * @return The major21AvgScore.
   */
  java.lang.String getMajor21AvgScore();
  /**
   * <pre>
   *21年平均分
   * </pre>
   *
   * <code>string major21AvgScore = 55;</code>
   * @return The bytes for major21AvgScore.
   */
  com.google.protobuf.ByteString
      getMajor21AvgScoreBytes();

  /**
   * <pre>
   *21年平均位次
   * </pre>
   *
   * <code>string major21AvgRank = 56;</code>
   * @return The major21AvgRank.
   */
  java.lang.String getMajor21AvgRank();
  /**
   * <pre>
   *21年平均位次
   * </pre>
   *
   * <code>string major21AvgRank = 56;</code>
   * @return The bytes for major21AvgRank.
   */
  com.google.protobuf.ByteString
      getMajor21AvgRankBytes();

  /**
   * <pre>
   *20年高分
   * </pre>
   *
   * <code>string major20HScore = 57;</code>
   * @return The major20HScore.
   */
  java.lang.String getMajor20HScore();
  /**
   * <pre>
   *20年高分
   * </pre>
   *
   * <code>string major20HScore = 57;</code>
   * @return The bytes for major20HScore.
   */
  com.google.protobuf.ByteString
      getMajor20HScoreBytes();

  /**
   * <pre>
   *20年高位次
   * </pre>
   *
   * <code>string major20HRank = 58;</code>
   * @return The major20HRank.
   */
  java.lang.String getMajor20HRank();
  /**
   * <pre>
   *20年高位次
   * </pre>
   *
   * <code>string major20HRank = 58;</code>
   * @return The bytes for major20HRank.
   */
  com.google.protobuf.ByteString
      getMajor20HRankBytes();

  /**
   * <pre>
   *20年平均分
   * </pre>
   *
   * <code>string major20AvgScore = 59;</code>
   * @return The major20AvgScore.
   */
  java.lang.String getMajor20AvgScore();
  /**
   * <pre>
   *20年平均分
   * </pre>
   *
   * <code>string major20AvgScore = 59;</code>
   * @return The bytes for major20AvgScore.
   */
  com.google.protobuf.ByteString
      getMajor20AvgScoreBytes();

  /**
   * <pre>
   *20年平均位次
   * </pre>
   *
   * <code>string major20AvgRank = 60;</code>
   * @return The major20AvgRank.
   */
  java.lang.String getMajor20AvgRank();
  /**
   * <pre>
   *20年平均位次
   * </pre>
   *
   * <code>string major20AvgRank = 60;</code>
   * @return The bytes for major20AvgRank.
   */
  com.google.protobuf.ByteString
      getMajor20AvgRankBytes();

  /**
   * <pre>
   *23计划数 = 组内求和
   * </pre>
   *
   * <code>string studentNum23Plan = 61;</code>
   * @return The studentNum23Plan.
   */
  java.lang.String getStudentNum23Plan();
  /**
   * <pre>
   *23计划数 = 组内求和
   * </pre>
   *
   * <code>string studentNum23Plan = 61;</code>
   * @return The bytes for studentNum23Plan.
   */
  com.google.protobuf.ByteString
      getStudentNum23PlanBytes();

  /**
   * <pre>
   *23年计划数
   * </pre>
   *
   * <code>string major23Plan = 62;</code>
   * @return The major23Plan.
   */
  java.lang.String getMajor23Plan();
  /**
   * <pre>
   *23年计划数
   * </pre>
   *
   * <code>string major23Plan = 62;</code>
   * @return The bytes for major23Plan.
   */
  com.google.protobuf.ByteString
      getMajor23PlanBytes();

  /**
   * <pre>
   *体检限报信息(a),(b)
   * </pre>
   *
   * <code>repeated string limitationInfos = 63;</code>
   * @return A list containing the limitationInfos.
   */
  java.util.List<java.lang.String>
      getLimitationInfosList();
  /**
   * <pre>
   *体检限报信息(a),(b)
   * </pre>
   *
   * <code>repeated string limitationInfos = 63;</code>
   * @return The count of limitationInfos.
   */
  int getLimitationInfosCount();
  /**
   * <pre>
   *体检限报信息(a),(b)
   * </pre>
   *
   * <code>repeated string limitationInfos = 63;</code>
   * @param index The index of the element to return.
   * @return The limitationInfos at the given index.
   */
  java.lang.String getLimitationInfos(int index);
  /**
   * <pre>
   *体检限报信息(a),(b)
   * </pre>
   *
   * <code>repeated string limitationInfos = 63;</code>
   * @param index The index of the value to return.
   * @return The bytes of the limitationInfos at the given index.
   */
  com.google.protobuf.ByteString
      getLimitationInfosBytes(int index);

  /**
   * <pre>
   *英语成绩
   * </pre>
   *
   * <code>int32 englishScore = 64;</code>
   * @return The englishScore.
   */
  int getEnglishScore();

  /**
   * <pre>
   *数学成绩
   * </pre>
   *
   * <code>int32 mathScore = 65;</code>
   * @return The mathScore.
   */
  int getMathScore();

  /**
   * <pre>
   * 被限制的专业字符名
   * </pre>
   *
   * <code>repeated string limitedMajorNames = 66;</code>
   * @return A list containing the limitedMajorNames.
   */
  java.util.List<java.lang.String>
      getLimitedMajorNamesList();
  /**
   * <pre>
   * 被限制的专业字符名
   * </pre>
   *
   * <code>repeated string limitedMajorNames = 66;</code>
   * @return The count of limitedMajorNames.
   */
  int getLimitedMajorNamesCount();
  /**
   * <pre>
   * 被限制的专业字符名
   * </pre>
   *
   * <code>repeated string limitedMajorNames = 66;</code>
   * @param index The index of the element to return.
   * @return The limitedMajorNames at the given index.
   */
  java.lang.String getLimitedMajorNames(int index);
  /**
   * <pre>
   * 被限制的专业字符名
   * </pre>
   *
   * <code>repeated string limitedMajorNames = 66;</code>
   * @param index The index of the value to return.
   * @return The bytes of the limitedMajorNames at the given index.
   */
  com.google.protobuf.ByteString
      getLimitedMajorNamesBytes(int index);

  /**
   * <pre>
   *被限制的专业字符 颜色, 2:红色,  3:黄色
   * </pre>
   *
   * <code>repeated int32 limitedMajorColor = 67;</code>
   * @return A list containing the limitedMajorColor.
   */
  java.util.List<java.lang.Integer> getLimitedMajorColorList();
  /**
   * <pre>
   *被限制的专业字符 颜色, 2:红色,  3:黄色
   * </pre>
   *
   * <code>repeated int32 limitedMajorColor = 67;</code>
   * @return The count of limitedMajorColor.
   */
  int getLimitedMajorColorCount();
  /**
   * <pre>
   *被限制的专业字符 颜色, 2:红色,  3:黄色
   * </pre>
   *
   * <code>repeated int32 limitedMajorColor = 67;</code>
   * @param index The index of the element to return.
   * @return The limitedMajorColor at the given index.
   */
  int getLimitedMajorColor(int index);

  /**
   * <pre>
   *年份
   * </pre>
   *
   * <code>string examYear = 68;</code>
   * @return The examYear.
   */
  java.lang.String getExamYear();
  /**
   * <pre>
   *年份
   * </pre>
   *
   * <code>string examYear = 68;</code>
   * @return The bytes for examYear.
   */
  com.google.protobuf.ByteString
      getExamYearBytes();

  /**
   * <pre>
   *身高限制
   * </pre>
   *
   * <code>string heightLimit = 69;</code>
   * @return The heightLimit.
   */
  java.lang.String getHeightLimit();
  /**
   * <pre>
   *身高限制
   * </pre>
   *
   * <code>string heightLimit = 69;</code>
   * @return The bytes for heightLimit.
   */
  com.google.protobuf.ByteString
      getHeightLimitBytes();

  /**
   * <pre>
   *专业类表 中 专业名 [id,id,id]
   * </pre>
   *
   * <code>repeated string majorNameDetails = 70;</code>
   * @return A list containing the majorNameDetails.
   */
  java.util.List<java.lang.String>
      getMajorNameDetailsList();
  /**
   * <pre>
   *专业类表 中 专业名 [id,id,id]
   * </pre>
   *
   * <code>repeated string majorNameDetails = 70;</code>
   * @return The count of majorNameDetails.
   */
  int getMajorNameDetailsCount();
  /**
   * <pre>
   *专业类表 中 专业名 [id,id,id]
   * </pre>
   *
   * <code>repeated string majorNameDetails = 70;</code>
   * @param index The index of the element to return.
   * @return The majorNameDetails at the given index.
   */
  java.lang.String getMajorNameDetails(int index);
  /**
   * <pre>
   *专业类表 中 专业名 [id,id,id]
   * </pre>
   *
   * <code>repeated string majorNameDetails = 70;</code>
   * @param index The index of the value to return.
   * @return The bytes of the majorNameDetails at the given index.
   */
  com.google.protobuf.ByteString
      getMajorNameDetailsBytes(int index);

  /**
   * <pre>
   *22组分数 女子
   * </pre>
   *
   * <code>string scoreFor22_nv = 71;</code>
   * @return The scoreFor22Nv.
   */
  java.lang.String getScoreFor22Nv();
  /**
   * <pre>
   *22组分数 女子
   * </pre>
   *
   * <code>string scoreFor22_nv = 71;</code>
   * @return The bytes for scoreFor22Nv.
   */
  com.google.protobuf.ByteString
      getScoreFor22NvBytes();

  /**
   * <pre>
   *22组位次 女子
   * </pre>
   *
   * <code>string rankFor22_nv = 72;</code>
   * @return The rankFor22Nv.
   */
  java.lang.String getRankFor22Nv();
  /**
   * <pre>
   *22组位次 女子
   * </pre>
   *
   * <code>string rankFor22_nv = 72;</code>
   * @return The bytes for rankFor22Nv.
   */
  com.google.protobuf.ByteString
      getRankFor22NvBytes();

  /**
   * <pre>
   *22年低 女子
   * </pre>
   *
   * <code>string major22LowScore_nv = 73;</code>
   * @return The major22LowScoreNv.
   */
  java.lang.String getMajor22LowScoreNv();
  /**
   * <pre>
   *22年低 女子
   * </pre>
   *
   * <code>string major22LowScore_nv = 73;</code>
   * @return The bytes for major22LowScoreNv.
   */
  com.google.protobuf.ByteString
      getMajor22LowScoreNvBytes();

  /**
   * <pre>
   *22年低位次 女子
   * </pre>
   *
   * <code>string major22LowRank_nv = 74;</code>
   * @return The major22LowRankNv.
   */
  java.lang.String getMajor22LowRankNv();
  /**
   * <pre>
   *22年低位次 女子
   * </pre>
   *
   * <code>string major22LowRank_nv = 74;</code>
   * @return The bytes for major22LowRankNv.
   */
  com.google.protobuf.ByteString
      getMajor22LowRankNvBytes();

  /**
   * <pre>
   *是否区分 男女分数 0: 不区分  1:区分男女
   * </pre>
   *
   * <code>int32 hasGenderScore = 75;</code>
   * @return The hasGenderScore.
   */
  int getHasGenderScore();

  /**
   * <pre>
   *是否中外合作;  用1表示  正
   * </pre>
   *
   * <code>int32 isZhongWai = 76;</code>
   * @return The isZhongWai.
   */
  int getIsZhongWai();

  /**
   * <pre>
   *是否本硕; 用1表示 正确
   * </pre>
   *
   * <code>int32 isBenSuo = 77;</code>
   * @return The isBenSuo.
   */
  int getIsBenSuo();

  /**
   * <pre>
   *保研率
   * </pre>
   *
   * <code>string baoYanLv = 78;</code>
   * @return The baoYanLv.
   */
  java.lang.String getBaoYanLv();
  /**
   * <pre>
   *保研率
   * </pre>
   *
   * <code>string baoYanLv = 78;</code>
   * @return The bytes for baoYanLv.
   */
  com.google.protobuf.ByteString
      getBaoYanLvBytes();

  /**
   * <pre>
   *升学率
   * </pre>
   *
   * <code>string shengXueLv = 79;</code>
   * @return The shengXueLv.
   */
  java.lang.String getShengXueLv();
  /**
   * <pre>
   *升学率
   * </pre>
   *
   * <code>string shengXueLv = 79;</code>
   * @return The bytes for shengXueLv.
   */
  com.google.protobuf.ByteString
      getShengXueLvBytes();

  /**
   * <pre>
   *专业类表 ids [id,id,id], 所有专业组内的专业id
   * </pre>
   *
   * <code>repeated fixed64 majorGroupClsIds = 80;</code>
   * @return A list containing the majorGroupClsIds.
   */
  java.util.List<java.lang.Long> getMajorGroupClsIdsList();
  /**
   * <pre>
   *专业类表 ids [id,id,id], 所有专业组内的专业id
   * </pre>
   *
   * <code>repeated fixed64 majorGroupClsIds = 80;</code>
   * @return The count of majorGroupClsIds.
   */
  int getMajorGroupClsIdsCount();
  /**
   * <pre>
   *专业类表 ids [id,id,id], 所有专业组内的专业id
   * </pre>
   *
   * <code>repeated fixed64 majorGroupClsIds = 80;</code>
   * @param index The index of the element to return.
   * @return The majorGroupClsIds at the given index.
   */
  long getMajorGroupClsIds(int index);

  /**
   * <pre>
   *所有专业组内的 专业名
   * </pre>
   *
   * <code>repeated string majorGroupMajorName = 81;</code>
   * @return A list containing the majorGroupMajorName.
   */
  java.util.List<java.lang.String>
      getMajorGroupMajorNameList();
  /**
   * <pre>
   *所有专业组内的 专业名
   * </pre>
   *
   * <code>repeated string majorGroupMajorName = 81;</code>
   * @return The count of majorGroupMajorName.
   */
  int getMajorGroupMajorNameCount();
  /**
   * <pre>
   *所有专业组内的 专业名
   * </pre>
   *
   * <code>repeated string majorGroupMajorName = 81;</code>
   * @param index The index of the element to return.
   * @return The majorGroupMajorName at the given index.
   */
  java.lang.String getMajorGroupMajorName(int index);
  /**
   * <pre>
   *所有专业组内的 专业名
   * </pre>
   *
   * <code>repeated string majorGroupMajorName = 81;</code>
   * @param index The index of the value to return.
   * @return The bytes of the majorGroupMajorName at the given index.
   */
  com.google.protobuf.ByteString
      getMajorGroupMajorNameBytes(int index);
}
